// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_JAVA_UTIL_FUNCTION_BOOLEANSUPPLIER_H
#define SCAPIX_JAVA_UTIL_FUNCTION_BOOLEANSUPPLIER_H

namespace scapix::java_api {
namespace java::util::function {

class BooleanSupplier : public object_base<SCAPIX_META_STRING("java/util/function/BooleanSupplier"),
	java::lang::Object>
{
public:

	jboolean getAsBoolean();

protected:

	BooleanSupplier(handle_type h) : base_(h) {}

};

} // namespace java::util::function
} // namespace scapix::java_api


namespace scapix::java_api {
namespace java::util::function {

inline jboolean BooleanSupplier::getAsBoolean() { return call_method<SCAPIX_META_STRING("getAsBoolean"), jboolean>(); }

} // namespace java::util::function
} // namespace scapix::java_api

#endif // SCAPIX_JAVA_UTIL_FUNCTION_BOOLEANSUPPLIER_H
