// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/util/IllegalFormatException.h>

#ifndef SCAPIX_JAVA_UTIL_MISSINGFORMATARGUMENTEXCEPTION_H
#define SCAPIX_JAVA_UTIL_MISSINGFORMATARGUMENTEXCEPTION_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace java::util {

class MissingFormatArgumentException : public object_base<SCAPIX_META_STRING("java/util/MissingFormatArgumentException"),
	java::util::IllegalFormatException>
{
public:

	static ref<MissingFormatArgumentException> new_object(ref<java::lang::String> s);
	ref<java::lang::String> getFormatSpecifier();
	ref<java::lang::String> getMessage();

protected:

	MissingFormatArgumentException(handle_type h) : base_(h) {}

};

} // namespace java::util
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace java::util {

inline ref<MissingFormatArgumentException> MissingFormatArgumentException::new_object(ref<java::lang::String> s) { return base_::new_object(s); }
inline ref<java::lang::String> MissingFormatArgumentException::getFormatSpecifier() { return call_method<SCAPIX_META_STRING("getFormatSpecifier"), ref<java::lang::String>>(); }
inline ref<java::lang::String> MissingFormatArgumentException::getMessage() { return call_method<SCAPIX_META_STRING("getMessage"), ref<java::lang::String>>(); }

} // namespace java::util
} // namespace scapix::java_api

#endif // SCAPIX_JAVA_UTIL_MISSINGFORMATARGUMENTEXCEPTION_H
