// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_ICU_LANG_UCHARACTER_GRAPHEMECLUSTERBREAK_H
#define SCAPIX_ANDROID_ICU_LANG_UCHARACTER_GRAPHEMECLUSTERBREAK_H

namespace scapix::java_api {


namespace android::icu::lang {

class UCharacter_GraphemeClusterBreak : public object_base<SCAPIX_META_STRING("android/icu/lang/UCharacter$GraphemeClusterBreak"),
	java::lang::Object>
{
public:

	static jint CONTROL_();
	static jint CR_();
	static jint EXTEND_();
	static jint E_BASE_();
	static jint E_BASE_GAZ_();
	static jint E_MODIFIER_();
	static jint GLUE_AFTER_ZWJ_();
	static jint L_();
	static jint LF_();
	static jint LV_();
	static jint LVT_();
	static jint OTHER_();
	static jint PREPEND_();
	static jint REGIONAL_INDICATOR_();
	static jint SPACING_MARK_();
	static jint T_();
	static jint V_();
	static jint ZWJ_();


protected:

	UCharacter_GraphemeClusterBreak(handle_type h) : base_(h) {}

};

} // namespace android::icu::lang
} // namespace scapix::java_api


namespace scapix::java_api {
namespace android::icu::lang {

inline jint UCharacter_GraphemeClusterBreak::CONTROL_() { return get_static_field<SCAPIX_META_STRING("CONTROL"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::CR_() { return get_static_field<SCAPIX_META_STRING("CR"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::EXTEND_() { return get_static_field<SCAPIX_META_STRING("EXTEND"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::E_BASE_() { return get_static_field<SCAPIX_META_STRING("E_BASE"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::E_BASE_GAZ_() { return get_static_field<SCAPIX_META_STRING("E_BASE_GAZ"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::E_MODIFIER_() { return get_static_field<SCAPIX_META_STRING("E_MODIFIER"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::GLUE_AFTER_ZWJ_() { return get_static_field<SCAPIX_META_STRING("GLUE_AFTER_ZWJ"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::L_() { return get_static_field<SCAPIX_META_STRING("L"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::LF_() { return get_static_field<SCAPIX_META_STRING("LF"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::LV_() { return get_static_field<SCAPIX_META_STRING("LV"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::LVT_() { return get_static_field<SCAPIX_META_STRING("LVT"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::OTHER_() { return get_static_field<SCAPIX_META_STRING("OTHER"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::PREPEND_() { return get_static_field<SCAPIX_META_STRING("PREPEND"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::REGIONAL_INDICATOR_() { return get_static_field<SCAPIX_META_STRING("REGIONAL_INDICATOR"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::SPACING_MARK_() { return get_static_field<SCAPIX_META_STRING("SPACING_MARK"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::T_() { return get_static_field<SCAPIX_META_STRING("T"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::V_() { return get_static_field<SCAPIX_META_STRING("V"), jint>(); }
inline jint UCharacter_GraphemeClusterBreak::ZWJ_() { return get_static_field<SCAPIX_META_STRING("ZWJ"), jint>(); }

} // namespace android::icu::lang
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_ICU_LANG_UCHARACTER_GRAPHEMECLUSTERBREAK_H
