// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ORG_XML_SAX_ATTRIBUTES_H
#define SCAPIX_ORG_XML_SAX_ATTRIBUTES_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace org::xml::sax {

class Attributes : public object_base<SCAPIX_META_STRING("org/xml/sax/Attributes"),
	java::lang::Object>
{
public:

	jint getLength();
	ref<java::lang::String> getURI(jint p1);
	ref<java::lang::String> getLocalName(jint p1);
	ref<java::lang::String> getQName(jint p1);
	ref<java::lang::String> getType(jint p1);
	ref<java::lang::String> getValue(jint p1);
	jint getIndex(ref<java::lang::String> p1, ref<java::lang::String> p2);
	jint getIndex(ref<java::lang::String> p1);
	ref<java::lang::String> getType(ref<java::lang::String> p1, ref<java::lang::String> p2);
	ref<java::lang::String> getType(ref<java::lang::String> p1);
	ref<java::lang::String> getValue(ref<java::lang::String> p1, ref<java::lang::String> p2);
	ref<java::lang::String> getValue(ref<java::lang::String> p1);

protected:

	Attributes(handle_type h) : base_(h) {}

};

} // namespace org::xml::sax
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace org::xml::sax {

inline jint Attributes::getLength() { return call_method<SCAPIX_META_STRING("getLength"), jint>(); }
inline ref<java::lang::String> Attributes::getURI(jint p1) { return call_method<SCAPIX_META_STRING("getURI"), ref<java::lang::String>>(p1); }
inline ref<java::lang::String> Attributes::getLocalName(jint p1) { return call_method<SCAPIX_META_STRING("getLocalName"), ref<java::lang::String>>(p1); }
inline ref<java::lang::String> Attributes::getQName(jint p1) { return call_method<SCAPIX_META_STRING("getQName"), ref<java::lang::String>>(p1); }
inline ref<java::lang::String> Attributes::getType(jint p1) { return call_method<SCAPIX_META_STRING("getType"), ref<java::lang::String>>(p1); }
inline ref<java::lang::String> Attributes::getValue(jint p1) { return call_method<SCAPIX_META_STRING("getValue"), ref<java::lang::String>>(p1); }
inline jint Attributes::getIndex(ref<java::lang::String> p1, ref<java::lang::String> p2) { return call_method<SCAPIX_META_STRING("getIndex"), jint>(p1, p2); }
inline jint Attributes::getIndex(ref<java::lang::String> p1) { return call_method<SCAPIX_META_STRING("getIndex"), jint>(p1); }
inline ref<java::lang::String> Attributes::getType(ref<java::lang::String> p1, ref<java::lang::String> p2) { return call_method<SCAPIX_META_STRING("getType"), ref<java::lang::String>>(p1, p2); }
inline ref<java::lang::String> Attributes::getType(ref<java::lang::String> p1) { return call_method<SCAPIX_META_STRING("getType"), ref<java::lang::String>>(p1); }
inline ref<java::lang::String> Attributes::getValue(ref<java::lang::String> p1, ref<java::lang::String> p2) { return call_method<SCAPIX_META_STRING("getValue"), ref<java::lang::String>>(p1, p2); }
inline ref<java::lang::String> Attributes::getValue(ref<java::lang::String> p1) { return call_method<SCAPIX_META_STRING("getValue"), ref<java::lang::String>>(p1); }

} // namespace org::xml::sax
} // namespace scapix::java_api

#endif // SCAPIX_ORG_XML_SAX_ATTRIBUTES_H
