// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/database/SQLException.h>

#ifndef SCAPIX_ANDROID_DATABASE_SQLITE_SQLITEEXCEPTION_H
#define SCAPIX_ANDROID_DATABASE_SQLITE_SQLITEEXCEPTION_H

namespace scapix::java_api {

namespace java::lang { class String; }
namespace java::lang { class Throwable; }

namespace android::database::sqlite {

class SQLiteException : public object_base<SCAPIX_META_STRING("android/database/sqlite/SQLiteException"),
	android::database::SQLException>
{
public:

	static ref<SQLiteException> new_object();
	static ref<SQLiteException> new_object(ref<java::lang::String> error);
	static ref<SQLiteException> new_object(ref<java::lang::String> error, ref<java::lang::Throwable> cause);

protected:

	SQLiteException(handle_type h) : base_(h) {}

};

} // namespace android::database::sqlite
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/lang/Throwable.h>

namespace scapix::java_api {
namespace android::database::sqlite {

inline ref<SQLiteException> SQLiteException::new_object() { return base_::new_object(); }
inline ref<SQLiteException> SQLiteException::new_object(ref<java::lang::String> error) { return base_::new_object(error); }
inline ref<SQLiteException> SQLiteException::new_object(ref<java::lang::String> error, ref<java::lang::Throwable> cause) { return base_::new_object(error, cause); }

} // namespace android::database::sqlite
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_DATABASE_SQLITE_SQLITEEXCEPTION_H
