// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/database/sqlite/SQLiteProgram.h>

#ifndef SCAPIX_ANDROID_DATABASE_SQLITE_SQLITEQUERY_H
#define SCAPIX_ANDROID_DATABASE_SQLITE_SQLITEQUERY_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace android::database::sqlite {

class SQLiteQuery : public object_base<SCAPIX_META_STRING("android/database/sqlite/SQLiteQuery"),
	android::database::sqlite::SQLiteProgram>
{
public:

	ref<java::lang::String> toString();

protected:

	SQLiteQuery(handle_type h) : base_(h) {}

};

} // namespace android::database::sqlite
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::database::sqlite {

inline ref<java::lang::String> SQLiteQuery::toString() { return call_method<SCAPIX_META_STRING("toString"), ref<java::lang::String>>(); }

} // namespace android::database::sqlite
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_DATABASE_SQLITE_SQLITEQUERY_H
