// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_GRAPHICS_PDF_PDFDOCUMENT_PAGE_H
#define SCAPIX_ANDROID_GRAPHICS_PDF_PDFDOCUMENT_PAGE_H

namespace scapix::java_api {

namespace android::graphics { class Canvas; }
namespace android::graphics::pdf { class PdfDocument_PageInfo; }

namespace android::graphics::pdf {

class PdfDocument_Page : public object_base<SCAPIX_META_STRING("android/graphics/pdf/PdfDocument$Page"),
	java::lang::Object>
{
public:

	ref<android::graphics::Canvas> getCanvas();
	ref<android::graphics::pdf::PdfDocument_PageInfo> getInfo();

protected:

	PdfDocument_Page(handle_type h) : base_(h) {}

};

} // namespace android::graphics::pdf
} // namespace scapix::java_api

#include <scapix/java_api/android/graphics/Canvas.h>
#include <scapix/java_api/android/graphics/pdf/PdfDocument_PageInfo.h>

namespace scapix::java_api {
namespace android::graphics::pdf {

inline ref<android::graphics::Canvas> PdfDocument_Page::getCanvas() { return call_method<SCAPIX_META_STRING("getCanvas"), ref<android::graphics::Canvas>>(); }
inline ref<android::graphics::pdf::PdfDocument_PageInfo> PdfDocument_Page::getInfo() { return call_method<SCAPIX_META_STRING("getInfo"), ref<android::graphics::pdf::PdfDocument_PageInfo>>(); }

} // namespace android::graphics::pdf
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_GRAPHICS_PDF_PDFDOCUMENT_PAGE_H
