// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_RENDERSCRIPT_DOUBLE3_H
#define SCAPIX_ANDROID_RENDERSCRIPT_DOUBLE3_H

namespace scapix::java_api {
namespace android::renderscript {

class Double3 : public object_base<SCAPIX_META_STRING("android/renderscript/Double3"),
	java::lang::Object>
{
public:

	jdouble x();
	void x(jdouble);
	jdouble y();
	void y(jdouble);
	jdouble z();
	void z(jdouble);

	static ref<Double3> new_object();
	static ref<Double3> new_object(jdouble x, jdouble p2, jdouble y);

protected:

	Double3(handle_type h) : base_(h) {}

};

} // namespace android::renderscript
} // namespace scapix::java_api


namespace scapix::java_api {
namespace android::renderscript {

inline jdouble Double3::x() { return get_field<SCAPIX_META_STRING("x"), jdouble>(); }
inline void Double3::x(jdouble v) { set_field<SCAPIX_META_STRING("x"), jdouble>(v); }
inline jdouble Double3::y() { return get_field<SCAPIX_META_STRING("y"), jdouble>(); }
inline void Double3::y(jdouble v) { set_field<SCAPIX_META_STRING("y"), jdouble>(v); }
inline jdouble Double3::z() { return get_field<SCAPIX_META_STRING("z"), jdouble>(); }
inline void Double3::z(jdouble v) { set_field<SCAPIX_META_STRING("z"), jdouble>(v); }
inline ref<Double3> Double3::new_object() { return base_::new_object(); }
inline ref<Double3> Double3::new_object(jdouble x, jdouble p2, jdouble y) { return base_::new_object(x, p2, y); }

} // namespace android::renderscript
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_RENDERSCRIPT_DOUBLE3_H
