// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/transition/PathMotion.h>

#ifndef SCAPIX_ANDROID_TRANSITION_PATTERNPATHMOTION_H
#define SCAPIX_ANDROID_TRANSITION_PATTERNPATHMOTION_H

namespace scapix::java_api {

namespace android::content { class Context; }
namespace android::graphics { class Path; }
namespace android::util { class AttributeSet; }

namespace android::transition {

class PatternPathMotion : public object_base<SCAPIX_META_STRING("android/transition/PatternPathMotion"),
	android::transition::PathMotion>
{
public:

	static ref<PatternPathMotion> new_object();
	static ref<PatternPathMotion> new_object(ref<android::content::Context> context, ref<android::util::AttributeSet> attrs);
	static ref<PatternPathMotion> new_object(ref<android::graphics::Path> patternPath);
	ref<android::graphics::Path> getPatternPath();
	void setPatternPath(ref<android::graphics::Path> patternPath);
	ref<android::graphics::Path> getPath(jfloat startX, jfloat startY, jfloat endX, jfloat endY);

protected:

	PatternPathMotion(handle_type h) : base_(h) {}

};

} // namespace android::transition
} // namespace scapix::java_api

#include <scapix/java_api/android/content/Context.h>
#include <scapix/java_api/android/graphics/Path.h>
#include <scapix/java_api/android/util/AttributeSet.h>

namespace scapix::java_api {
namespace android::transition {

inline ref<PatternPathMotion> PatternPathMotion::new_object() { return base_::new_object(); }
inline ref<PatternPathMotion> PatternPathMotion::new_object(ref<android::content::Context> context, ref<android::util::AttributeSet> attrs) { return base_::new_object(context, attrs); }
inline ref<PatternPathMotion> PatternPathMotion::new_object(ref<android::graphics::Path> patternPath) { return base_::new_object(patternPath); }
inline ref<android::graphics::Path> PatternPathMotion::getPatternPath() { return call_method<SCAPIX_META_STRING("getPatternPath"), ref<android::graphics::Path>>(); }
inline void PatternPathMotion::setPatternPath(ref<android::graphics::Path> patternPath) { return call_method<SCAPIX_META_STRING("setPatternPath"), void>(patternPath); }
inline ref<android::graphics::Path> PatternPathMotion::getPath(jfloat startX, jfloat startY, jfloat endX, jfloat endY) { return call_method<SCAPIX_META_STRING("getPath"), ref<android::graphics::Path>>(startX, startY, endX, endY); }

} // namespace android::transition
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_TRANSITION_PATTERNPATHMOTION_H
