// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Error.h>

#ifndef SCAPIX_JAVA_LANG_ANNOTATION_ANNOTATIONFORMATERROR_H
#define SCAPIX_JAVA_LANG_ANNOTATION_ANNOTATIONFORMATERROR_H

namespace scapix::java_api {

namespace java::lang { class String; }
namespace java::lang { class Throwable; }

namespace java::lang::annotation {

class AnnotationFormatError : public object_base<SCAPIX_META_STRING("java/lang/annotation/AnnotationFormatError"),
	java::lang::Error>
{
public:

	static ref<AnnotationFormatError> new_object(ref<java::lang::String> message);
	static ref<AnnotationFormatError> new_object(ref<java::lang::String> message, ref<java::lang::Throwable> cause);
	static ref<AnnotationFormatError> new_object(ref<java::lang::Throwable> cause);

protected:

	AnnotationFormatError(handle_type h) : base_(h) {}

};

} // namespace java::lang::annotation
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/lang/Throwable.h>

namespace scapix::java_api {
namespace java::lang::annotation {

inline ref<AnnotationFormatError> AnnotationFormatError::new_object(ref<java::lang::String> message) { return base_::new_object(message); }
inline ref<AnnotationFormatError> AnnotationFormatError::new_object(ref<java::lang::String> message, ref<java::lang::Throwable> cause) { return base_::new_object(message, cause); }
inline ref<AnnotationFormatError> AnnotationFormatError::new_object(ref<java::lang::Throwable> cause) { return base_::new_object(cause); }

} // namespace java::lang::annotation
} // namespace scapix::java_api

#endif // SCAPIX_JAVA_LANG_ANNOTATION_ANNOTATIONFORMATERROR_H
