// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/app/Activity.h>

#ifndef SCAPIX_ANDROID_ACCOUNTS_ACCOUNTAUTHENTICATORACTIVITY_H
#define SCAPIX_ANDROID_ACCOUNTS_ACCOUNTAUTHENTICATORACTIVITY_H

namespace scapix::java_api {

namespace android::os { class Bundle; }

namespace android::accounts {

class AccountAuthenticatorActivity : public object_base<SCAPIX_META_STRING("android/accounts/AccountAuthenticatorActivity"),
	android::app::Activity>
{
public:

	static ref<AccountAuthenticatorActivity> new_object();
	void setAccountAuthenticatorResult(ref<android::os::Bundle> result);
	void finish();

protected:

	AccountAuthenticatorActivity(handle_type h) : base_(h) {}

};

} // namespace android::accounts
} // namespace scapix::java_api

#include <scapix/java_api/android/os/Bundle.h>

namespace scapix::java_api {
namespace android::accounts {

inline ref<AccountAuthenticatorActivity> AccountAuthenticatorActivity::new_object() { return base_::new_object(); }
inline void AccountAuthenticatorActivity::setAccountAuthenticatorResult(ref<android::os::Bundle> result) { return call_method<SCAPIX_META_STRING("setAccountAuthenticatorResult"), void>(result); }
inline void AccountAuthenticatorActivity::finish() { return call_method<SCAPIX_META_STRING("finish"), void>(); }

} // namespace android::accounts
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_ACCOUNTS_ACCOUNTAUTHENTICATORACTIVITY_H
