// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_MEDIA_MICROPHONEINFO_COORDINATE3F_H
#define SCAPIX_ANDROID_MEDIA_MICROPHONEINFO_COORDINATE3F_H

namespace scapix::java_api {


namespace android::media {

class MicrophoneInfo_Coordinate3F : public object_base<SCAPIX_META_STRING("android/media/MicrophoneInfo$Coordinate3F"),
	java::lang::Object>
{
public:

	jfloat x();
	jfloat y();
	jfloat z();

	jboolean equals(ref<java::lang::Object> obj);

protected:

	MicrophoneInfo_Coordinate3F(handle_type h) : base_(h) {}

};

} // namespace android::media
} // namespace scapix::java_api


namespace scapix::java_api {
namespace android::media {

inline jfloat MicrophoneInfo_Coordinate3F::x() { return get_field<SCAPIX_META_STRING("x"), jfloat>(); }
inline jfloat MicrophoneInfo_Coordinate3F::y() { return get_field<SCAPIX_META_STRING("y"), jfloat>(); }
inline jfloat MicrophoneInfo_Coordinate3F::z() { return get_field<SCAPIX_META_STRING("z"), jfloat>(); }
inline jboolean MicrophoneInfo_Coordinate3F::equals(ref<java::lang::Object> obj) { return call_method<SCAPIX_META_STRING("equals"), jboolean>(obj); }

} // namespace android::media
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_MEDIA_MICROPHONEINFO_COORDINATE3F_H
