// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_NET_RTP_AUDIOCODEC_H
#define SCAPIX_ANDROID_NET_RTP_AUDIOCODEC_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace android::net::rtp {

class AudioCodec : public object_base<SCAPIX_META_STRING("android/net/rtp/AudioCodec"),
	java::lang::Object>
{
public:

	static ref<android::net::rtp::AudioCodec> AMR_();
	static ref<android::net::rtp::AudioCodec> GSM_();
	static ref<android::net::rtp::AudioCodec> GSM_EFR_();
	static ref<android::net::rtp::AudioCodec> PCMA_();
	static ref<android::net::rtp::AudioCodec> PCMU_();
	ref<java::lang::String> fmtp();
	ref<java::lang::String> rtpmap();
	jint type();

	static ref<link::java::array<android::net::rtp::AudioCodec>> getCodecs();
	static ref<android::net::rtp::AudioCodec> getCodec(jint type, ref<java::lang::String> rtpmap, ref<java::lang::String> fmtp);

protected:

	AudioCodec(handle_type h) : base_(h) {}

};

} // namespace android::net::rtp
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::net::rtp {

inline ref<android::net::rtp::AudioCodec> AudioCodec::AMR_() { return get_static_field<SCAPIX_META_STRING("AMR"), ref<android::net::rtp::AudioCodec>>(); }
inline ref<android::net::rtp::AudioCodec> AudioCodec::GSM_() { return get_static_field<SCAPIX_META_STRING("GSM"), ref<android::net::rtp::AudioCodec>>(); }
inline ref<android::net::rtp::AudioCodec> AudioCodec::GSM_EFR_() { return get_static_field<SCAPIX_META_STRING("GSM_EFR"), ref<android::net::rtp::AudioCodec>>(); }
inline ref<android::net::rtp::AudioCodec> AudioCodec::PCMA_() { return get_static_field<SCAPIX_META_STRING("PCMA"), ref<android::net::rtp::AudioCodec>>(); }
inline ref<android::net::rtp::AudioCodec> AudioCodec::PCMU_() { return get_static_field<SCAPIX_META_STRING("PCMU"), ref<android::net::rtp::AudioCodec>>(); }
inline ref<java::lang::String> AudioCodec::fmtp() { return get_field<SCAPIX_META_STRING("fmtp"), ref<java::lang::String>>(); }
inline ref<java::lang::String> AudioCodec::rtpmap() { return get_field<SCAPIX_META_STRING("rtpmap"), ref<java::lang::String>>(); }
inline jint AudioCodec::type() { return get_field<SCAPIX_META_STRING("type"), jint>(); }
inline ref<link::java::array<android::net::rtp::AudioCodec>> AudioCodec::getCodecs() { return call_static_method<SCAPIX_META_STRING("getCodecs"), ref<link::java::array<android::net::rtp::AudioCodec>>>(); }
inline ref<android::net::rtp::AudioCodec> AudioCodec::getCodec(jint type, ref<java::lang::String> rtpmap, ref<java::lang::String> fmtp) { return call_static_method<SCAPIX_META_STRING("getCodec"), ref<android::net::rtp::AudioCodec>>(type, rtpmap, fmtp); }

} // namespace android::net::rtp
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_NET_RTP_AUDIOCODEC_H
