// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/widget/CursorTreeAdapter.h>

#ifndef SCAPIX_ANDROID_WIDGET_RESOURCECURSORTREEADAPTER_H
#define SCAPIX_ANDROID_WIDGET_RESOURCECURSORTREEADAPTER_H

namespace scapix::java_api {

namespace android::content { class Context; }
namespace android::database { class Cursor; }
namespace android::view { class View; }
namespace android::view { class ViewGroup; }

namespace android::widget {

class ResourceCursorTreeAdapter : public object_base<SCAPIX_META_STRING("android/widget/ResourceCursorTreeAdapter"),
	android::widget::CursorTreeAdapter>
{
public:

	static ref<ResourceCursorTreeAdapter> new_object(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jint collapsedGroupLayout, jint expandedGroupLayout, jint childLayout, jint lastChildLayout);
	static ref<ResourceCursorTreeAdapter> new_object(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jint collapsedGroupLayout, jint expandedGroupLayout, jint childLayout);
	static ref<ResourceCursorTreeAdapter> new_object(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jint groupLayout, jint childLayout);
	ref<android::view::View> newChildView(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jboolean isLastChild, ref<android::view::ViewGroup> parent);
	ref<android::view::View> newGroupView(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jboolean isExpanded, ref<android::view::ViewGroup> parent);

protected:

	ResourceCursorTreeAdapter(handle_type h) : base_(h) {}

};

} // namespace android::widget
} // namespace scapix::java_api

#include <scapix/java_api/android/content/Context.h>
#include <scapix/java_api/android/database/Cursor.h>
#include <scapix/java_api/android/view/View.h>
#include <scapix/java_api/android/view/ViewGroup.h>

namespace scapix::java_api {
namespace android::widget {

inline ref<ResourceCursorTreeAdapter> ResourceCursorTreeAdapter::new_object(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jint collapsedGroupLayout, jint expandedGroupLayout, jint childLayout, jint lastChildLayout) { return base_::new_object(context, cursor, collapsedGroupLayout, expandedGroupLayout, childLayout, lastChildLayout); }
inline ref<ResourceCursorTreeAdapter> ResourceCursorTreeAdapter::new_object(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jint collapsedGroupLayout, jint expandedGroupLayout, jint childLayout) { return base_::new_object(context, cursor, collapsedGroupLayout, expandedGroupLayout, childLayout); }
inline ref<ResourceCursorTreeAdapter> ResourceCursorTreeAdapter::new_object(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jint groupLayout, jint childLayout) { return base_::new_object(context, cursor, groupLayout, childLayout); }
inline ref<android::view::View> ResourceCursorTreeAdapter::newChildView(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jboolean isLastChild, ref<android::view::ViewGroup> parent) { return call_method<SCAPIX_META_STRING("newChildView"), ref<android::view::View>>(context, cursor, isLastChild, parent); }
inline ref<android::view::View> ResourceCursorTreeAdapter::newGroupView(ref<android::content::Context> context, ref<android::database::Cursor> cursor, jboolean isExpanded, ref<android::view::ViewGroup> parent) { return call_method<SCAPIX_META_STRING("newGroupView"), ref<android::view::View>>(context, cursor, isExpanded, parent); }

} // namespace android::widget
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_WIDGET_RESOURCECURSORTREEADAPTER_H
