// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_WIDGET_TABHOST_TABCONTENTFACTORY_H
#define SCAPIX_ANDROID_WIDGET_TABHOST_TABCONTENTFACTORY_H

namespace scapix::java_api {

namespace android::view { class View; }
namespace java::lang { class String; }

namespace android::widget {

class TabHost_TabContentFactory : public object_base<SCAPIX_META_STRING("android/widget/TabHost$TabContentFactory"),
	java::lang::Object>
{
public:

	ref<android::view::View> createTabContent(ref<java::lang::String> p1);

protected:

	TabHost_TabContentFactory(handle_type h) : base_(h) {}

};

} // namespace android::widget
} // namespace scapix::java_api

#include <scapix/java_api/android/view/View.h>
#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::widget {

inline ref<android::view::View> TabHost_TabContentFactory::createTabContent(ref<java::lang::String> p1) { return call_method<SCAPIX_META_STRING("createTabContent"), ref<android::view::View>>(p1); }

} // namespace android::widget
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_WIDGET_TABHOST_TABCONTENTFACTORY_H
