// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/widget/SpinnerAdapter.h>

#ifndef SCAPIX_ANDROID_WIDGET_THEMEDSPINNERADAPTER_H
#define SCAPIX_ANDROID_WIDGET_THEMEDSPINNERADAPTER_H

namespace scapix::java_api {

namespace android::content::res { class Resources_Theme; }

namespace android::widget {

class ThemedSpinnerAdapter : public object_base<SCAPIX_META_STRING("android/widget/ThemedSpinnerAdapter"),
	java::lang::Object,
	android::widget::SpinnerAdapter>
{
public:

	void setDropDownViewTheme(ref<android::content::res::Resources_Theme> p1);
	ref<android::content::res::Resources_Theme> getDropDownViewTheme();

protected:

	ThemedSpinnerAdapter(handle_type h) : base_(h) {}

};

} // namespace android::widget
} // namespace scapix::java_api

#include <scapix/java_api/android/content/res/Resources_Theme.h>

namespace scapix::java_api {
namespace android::widget {

inline void ThemedSpinnerAdapter::setDropDownViewTheme(ref<android::content::res::Resources_Theme> p1) { return call_method<SCAPIX_META_STRING("setDropDownViewTheme"), void>(p1); }
inline ref<android::content::res::Resources_Theme> ThemedSpinnerAdapter::getDropDownViewTheme() { return call_method<SCAPIX_META_STRING("getDropDownViewTheme"), ref<android::content::res::Resources_Theme>>(); }

} // namespace android::widget
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_WIDGET_THEMEDSPINNERADAPTER_H
