// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_APP_BACKUP_BACKUPMANAGER_H
#define SCAPIX_ANDROID_APP_BACKUP_BACKUPMANAGER_H

namespace scapix::java_api {

namespace android::app::backup { class RestoreObserver; }
namespace android::content { class Context; }
namespace java::lang { class String; }

namespace android::app::backup {

class BackupManager : public object_base<SCAPIX_META_STRING("android/app/backup/BackupManager"),
	java::lang::Object>
{
public:

	static ref<BackupManager> new_object(ref<android::content::Context> context);
	void dataChanged();
	static void dataChanged(ref<java::lang::String> packageName);
	jint requestRestore(ref<android::app::backup::RestoreObserver> observer);

protected:

	BackupManager(handle_type h) : base_(h) {}

};

} // namespace android::app::backup
} // namespace scapix::java_api

#include <scapix/java_api/android/app/backup/RestoreObserver.h>
#include <scapix/java_api/android/content/Context.h>
#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::app::backup {

inline ref<BackupManager> BackupManager::new_object(ref<android::content::Context> context) { return base_::new_object(context); }
inline void BackupManager::dataChanged() { return call_method<SCAPIX_META_STRING("dataChanged"), void>(); }
inline void BackupManager::dataChanged(ref<java::lang::String> packageName) { return call_static_method<SCAPIX_META_STRING("dataChanged"), void>(packageName); }
inline jint BackupManager::requestRestore(ref<android::app::backup::RestoreObserver> observer) { return call_method<SCAPIX_META_STRING("requestRestore"), jint>(observer); }

} // namespace android::app::backup
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_APP_BACKUP_BACKUPMANAGER_H
