// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/util/AndroidRuntimeException.h>

#ifndef SCAPIX_ANDROID_CONTENT_RECEIVERCALLNOTALLOWEDEXCEPTION_H
#define SCAPIX_ANDROID_CONTENT_RECEIVERCALLNOTALLOWEDEXCEPTION_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace android::content {

class ReceiverCallNotAllowedException : public object_base<SCAPIX_META_STRING("android/content/ReceiverCallNotAllowedException"),
	android::util::AndroidRuntimeException>
{
public:

	static ref<ReceiverCallNotAllowedException> new_object(ref<java::lang::String> msg);

protected:

	ReceiverCallNotAllowedException(handle_type h) : base_(h) {}

};

} // namespace android::content
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::content {

inline ref<ReceiverCallNotAllowedException> ReceiverCallNotAllowedException::new_object(ref<java::lang::String> msg) { return base_::new_object(msg); }

} // namespace android::content
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_CONTENT_RECEIVERCALLNOTALLOWEDEXCEPTION_H
