// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/os/Parcelable.h>

#ifndef SCAPIX_ANDROID_CONTENT_URIPERMISSION_H
#define SCAPIX_ANDROID_CONTENT_URIPERMISSION_H

namespace scapix::java_api {

namespace android::net { class Uri; }
namespace android::os { class Parcel; }
namespace android::os { class Parcelable_Creator; }
namespace java::lang { class String; }

namespace android::content {

class UriPermission : public object_base<SCAPIX_META_STRING("android/content/UriPermission"),
	java::lang::Object,
	android::os::Parcelable>
{
public:

	static ref<android::os::Parcelable_Creator> CREATOR_();
	static jlong INVALID_TIME_();

	ref<android::net::Uri> getUri();
	jboolean isReadPermission();
	jboolean isWritePermission();
	jlong getPersistedTime();
	ref<java::lang::String> toString();
	jint describeContents();
	void writeToParcel(ref<android::os::Parcel> dest, jint flags);

protected:

	UriPermission(handle_type h) : base_(h) {}

};

} // namespace android::content
} // namespace scapix::java_api

#include <scapix/java_api/android/net/Uri.h>
#include <scapix/java_api/android/os/Parcel.h>
#include <scapix/java_api/android/os/Parcelable_Creator.h>
#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::content {

inline ref<android::os::Parcelable_Creator> UriPermission::CREATOR_() { return get_static_field<SCAPIX_META_STRING("CREATOR"), ref<android::os::Parcelable_Creator>>(); }
inline jlong UriPermission::INVALID_TIME_() { return get_static_field<SCAPIX_META_STRING("INVALID_TIME"), jlong>(); }
inline ref<android::net::Uri> UriPermission::getUri() { return call_method<SCAPIX_META_STRING("getUri"), ref<android::net::Uri>>(); }
inline jboolean UriPermission::isReadPermission() { return call_method<SCAPIX_META_STRING("isReadPermission"), jboolean>(); }
inline jboolean UriPermission::isWritePermission() { return call_method<SCAPIX_META_STRING("isWritePermission"), jboolean>(); }
inline jlong UriPermission::getPersistedTime() { return call_method<SCAPIX_META_STRING("getPersistedTime"), jlong>(); }
inline ref<java::lang::String> UriPermission::toString() { return call_method<SCAPIX_META_STRING("toString"), ref<java::lang::String>>(); }
inline jint UriPermission::describeContents() { return call_method<SCAPIX_META_STRING("describeContents"), jint>(); }
inline void UriPermission::writeToParcel(ref<android::os::Parcel> dest, jint flags) { return call_method<SCAPIX_META_STRING("writeToParcel"), void>(dest, flags); }

} // namespace android::content
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_CONTENT_URIPERMISSION_H
