// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/security/Permission.h>
#include <scapix/java_api/java/io/Serializable.h>

#ifndef SCAPIX_JAVA_NET_SOCKETPERMISSION_H
#define SCAPIX_JAVA_NET_SOCKETPERMISSION_H

namespace scapix::java_api {

namespace java::lang { class Object; }
namespace java::lang { class String; }
namespace java::security { class PermissionCollection; }

namespace java::net {

class SocketPermission : public object_base<SCAPIX_META_STRING("java/net/SocketPermission"),
	java::security::Permission,
	java::io::Serializable>
{
public:

	static ref<SocketPermission> new_object(ref<java::lang::String> host, ref<java::lang::String> action);
	jboolean implies(ref<java::security::Permission> p);
	jboolean equals(ref<java::lang::Object> obj);
	jint hashCode();
	ref<java::lang::String> getActions();
	ref<java::security::PermissionCollection> newPermissionCollection();

protected:

	SocketPermission(handle_type h) : base_(h) {}

};

} // namespace java::net
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/security/PermissionCollection.h>

namespace scapix::java_api {
namespace java::net {

inline ref<SocketPermission> SocketPermission::new_object(ref<java::lang::String> host, ref<java::lang::String> action) { return base_::new_object(host, action); }
inline jboolean SocketPermission::implies(ref<java::security::Permission> p) { return call_method<SCAPIX_META_STRING("implies"), jboolean>(p); }
inline jboolean SocketPermission::equals(ref<java::lang::Object> obj) { return call_method<SCAPIX_META_STRING("equals"), jboolean>(obj); }
inline jint SocketPermission::hashCode() { return call_method<SCAPIX_META_STRING("hashCode"), jint>(); }
inline ref<java::lang::String> SocketPermission::getActions() { return call_method<SCAPIX_META_STRING("getActions"), ref<java::lang::String>>(); }
inline ref<java::security::PermissionCollection> SocketPermission::newPermissionCollection() { return call_method<SCAPIX_META_STRING("newPermissionCollection"), ref<java::security::PermissionCollection>>(); }

} // namespace java::net
} // namespace scapix::java_api

#endif // SCAPIX_JAVA_NET_SOCKETPERMISSION_H
