// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/graphics/drawable/Drawable.h>

#ifndef SCAPIX_ANDROID_GRAPHICS_DRAWABLE_BITMAPDRAWABLE_H
#define SCAPIX_ANDROID_GRAPHICS_DRAWABLE_BITMAPDRAWABLE_H

namespace scapix::java_api {

namespace android::content::res { class ColorStateList; }
namespace android::content::res { class Resources; }
namespace android::content::res { class Resources_Theme; }
namespace android::graphics { class Bitmap; }
namespace android::graphics { class Canvas; }
namespace android::graphics { class ColorFilter; }
namespace android::graphics { class Outline; }
namespace android::graphics { class Paint; }
namespace android::graphics { class PorterDuff_Mode; }
namespace android::graphics { class Shader_TileMode; }
namespace android::graphics::drawable { class Drawable_ConstantState; }
namespace android::util { class AttributeSet; }
namespace android::util { class DisplayMetrics; }
namespace java::io { class InputStream; }
namespace java::lang { class String; }
namespace org::xmlpull::v1 { class XmlPullParser; }

namespace android::graphics::drawable {

class BitmapDrawable : public object_base<SCAPIX_META_STRING("android/graphics/drawable/BitmapDrawable"),
	android::graphics::drawable::Drawable>
{
public:

	static ref<BitmapDrawable> new_object();
	static ref<BitmapDrawable> new_object(ref<android::content::res::Resources> res);
	static ref<BitmapDrawable> new_object(ref<android::graphics::Bitmap> bitmap);
	static ref<BitmapDrawable> new_object(ref<android::content::res::Resources> res, ref<android::graphics::Bitmap> bitmap);
	static ref<BitmapDrawable> new_object(ref<java::lang::String> filepath);
	static ref<BitmapDrawable> new_object(ref<android::content::res::Resources> res, ref<java::lang::String> filepath);
	static ref<BitmapDrawable> new_object(ref<java::io::InputStream> is);
	static ref<BitmapDrawable> new_object(ref<android::content::res::Resources> res, ref<java::io::InputStream> is);
	ref<android::graphics::Paint> getPaint();
	ref<android::graphics::Bitmap> getBitmap();
	void setTargetDensity(ref<android::graphics::Canvas> canvas);
	void setTargetDensity(ref<android::util::DisplayMetrics> metrics);
	void setTargetDensity(jint density);
	jint getGravity();
	void setGravity(jint gravity);
	void setMipMap(jboolean mipMap);
	jboolean hasMipMap();
	void setAntiAlias(jboolean aa);
	jboolean hasAntiAlias();
	void setFilterBitmap(jboolean filter);
	jboolean isFilterBitmap();
	void setDither(jboolean dither);
	ref<android::graphics::Shader_TileMode> getTileModeX();
	ref<android::graphics::Shader_TileMode> getTileModeY();
	void setTileModeX(ref<android::graphics::Shader_TileMode> mode);
	void setTileModeY(ref<android::graphics::Shader_TileMode> mode);
	void setTileModeXY(ref<android::graphics::Shader_TileMode> xmode, ref<android::graphics::Shader_TileMode> ymode);
	void setAutoMirrored(jboolean mirrored);
	jboolean isAutoMirrored();
	jint getChangingConfigurations();
	void draw(ref<android::graphics::Canvas> canvas);
	void getOutline(ref<android::graphics::Outline> outline);
	void setAlpha(jint alpha);
	jint getAlpha();
	void setColorFilter(ref<android::graphics::ColorFilter> colorFilter);
	ref<android::graphics::ColorFilter> getColorFilter();
	void setTintList(ref<android::content::res::ColorStateList> tint);
	void setTintMode(ref<android::graphics::PorterDuff_Mode> tintMode);
	ref<android::graphics::drawable::Drawable> mutate();
	jboolean isStateful();
	void inflate(ref<android::content::res::Resources> r, ref<org::xmlpull::v1::XmlPullParser> parser, ref<android::util::AttributeSet> attrs, ref<android::content::res::Resources_Theme> theme);
	void applyTheme(ref<android::content::res::Resources_Theme> t);
	jboolean canApplyTheme();
	jint getIntrinsicWidth();
	jint getIntrinsicHeight();
	jint getOpacity();
	ref<android::graphics::drawable::Drawable_ConstantState> getConstantState();

protected:

	BitmapDrawable(handle_type h) : base_(h) {}

};

} // namespace android::graphics::drawable
} // namespace scapix::java_api

#include <scapix/java_api/android/content/res/ColorStateList.h>
#include <scapix/java_api/android/content/res/Resources.h>
#include <scapix/java_api/android/content/res/Resources_Theme.h>
#include <scapix/java_api/android/graphics/Bitmap.h>
#include <scapix/java_api/android/graphics/Canvas.h>
#include <scapix/java_api/android/graphics/ColorFilter.h>
#include <scapix/java_api/android/graphics/Outline.h>
#include <scapix/java_api/android/graphics/Paint.h>
#include <scapix/java_api/android/graphics/PorterDuff_Mode.h>
#include <scapix/java_api/android/graphics/Shader_TileMode.h>
#include <scapix/java_api/android/graphics/drawable/Drawable_ConstantState.h>
#include <scapix/java_api/android/util/AttributeSet.h>
#include <scapix/java_api/android/util/DisplayMetrics.h>
#include <scapix/java_api/java/io/InputStream.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/org/xmlpull/v1/XmlPullParser.h>

namespace scapix::java_api {
namespace android::graphics::drawable {

inline ref<BitmapDrawable> BitmapDrawable::new_object() { return base_::new_object(); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<android::content::res::Resources> res) { return base_::new_object(res); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<android::graphics::Bitmap> bitmap) { return base_::new_object(bitmap); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<android::content::res::Resources> res, ref<android::graphics::Bitmap> bitmap) { return base_::new_object(res, bitmap); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<java::lang::String> filepath) { return base_::new_object(filepath); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<android::content::res::Resources> res, ref<java::lang::String> filepath) { return base_::new_object(res, filepath); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<java::io::InputStream> is) { return base_::new_object(is); }
inline ref<BitmapDrawable> BitmapDrawable::new_object(ref<android::content::res::Resources> res, ref<java::io::InputStream> is) { return base_::new_object(res, is); }
inline ref<android::graphics::Paint> BitmapDrawable::getPaint() { return call_method<SCAPIX_META_STRING("getPaint"), ref<android::graphics::Paint>>(); }
inline ref<android::graphics::Bitmap> BitmapDrawable::getBitmap() { return call_method<SCAPIX_META_STRING("getBitmap"), ref<android::graphics::Bitmap>>(); }
inline void BitmapDrawable::setTargetDensity(ref<android::graphics::Canvas> canvas) { return call_method<SCAPIX_META_STRING("setTargetDensity"), void>(canvas); }
inline void BitmapDrawable::setTargetDensity(ref<android::util::DisplayMetrics> metrics) { return call_method<SCAPIX_META_STRING("setTargetDensity"), void>(metrics); }
inline void BitmapDrawable::setTargetDensity(jint density) { return call_method<SCAPIX_META_STRING("setTargetDensity"), void>(density); }
inline jint BitmapDrawable::getGravity() { return call_method<SCAPIX_META_STRING("getGravity"), jint>(); }
inline void BitmapDrawable::setGravity(jint gravity) { return call_method<SCAPIX_META_STRING("setGravity"), void>(gravity); }
inline void BitmapDrawable::setMipMap(jboolean mipMap) { return call_method<SCAPIX_META_STRING("setMipMap"), void>(mipMap); }
inline jboolean BitmapDrawable::hasMipMap() { return call_method<SCAPIX_META_STRING("hasMipMap"), jboolean>(); }
inline void BitmapDrawable::setAntiAlias(jboolean aa) { return call_method<SCAPIX_META_STRING("setAntiAlias"), void>(aa); }
inline jboolean BitmapDrawable::hasAntiAlias() { return call_method<SCAPIX_META_STRING("hasAntiAlias"), jboolean>(); }
inline void BitmapDrawable::setFilterBitmap(jboolean filter) { return call_method<SCAPIX_META_STRING("setFilterBitmap"), void>(filter); }
inline jboolean BitmapDrawable::isFilterBitmap() { return call_method<SCAPIX_META_STRING("isFilterBitmap"), jboolean>(); }
inline void BitmapDrawable::setDither(jboolean dither) { return call_method<SCAPIX_META_STRING("setDither"), void>(dither); }
inline ref<android::graphics::Shader_TileMode> BitmapDrawable::getTileModeX() { return call_method<SCAPIX_META_STRING("getTileModeX"), ref<android::graphics::Shader_TileMode>>(); }
inline ref<android::graphics::Shader_TileMode> BitmapDrawable::getTileModeY() { return call_method<SCAPIX_META_STRING("getTileModeY"), ref<android::graphics::Shader_TileMode>>(); }
inline void BitmapDrawable::setTileModeX(ref<android::graphics::Shader_TileMode> mode) { return call_method<SCAPIX_META_STRING("setTileModeX"), void>(mode); }
inline void BitmapDrawable::setTileModeY(ref<android::graphics::Shader_TileMode> mode) { return call_method<SCAPIX_META_STRING("setTileModeY"), void>(mode); }
inline void BitmapDrawable::setTileModeXY(ref<android::graphics::Shader_TileMode> xmode, ref<android::graphics::Shader_TileMode> ymode) { return call_method<SCAPIX_META_STRING("setTileModeXY"), void>(xmode, ymode); }
inline void BitmapDrawable::setAutoMirrored(jboolean mirrored) { return call_method<SCAPIX_META_STRING("setAutoMirrored"), void>(mirrored); }
inline jboolean BitmapDrawable::isAutoMirrored() { return call_method<SCAPIX_META_STRING("isAutoMirrored"), jboolean>(); }
inline jint BitmapDrawable::getChangingConfigurations() { return call_method<SCAPIX_META_STRING("getChangingConfigurations"), jint>(); }
inline void BitmapDrawable::draw(ref<android::graphics::Canvas> canvas) { return call_method<SCAPIX_META_STRING("draw"), void>(canvas); }
inline void BitmapDrawable::getOutline(ref<android::graphics::Outline> outline) { return call_method<SCAPIX_META_STRING("getOutline"), void>(outline); }
inline void BitmapDrawable::setAlpha(jint alpha) { return call_method<SCAPIX_META_STRING("setAlpha"), void>(alpha); }
inline jint BitmapDrawable::getAlpha() { return call_method<SCAPIX_META_STRING("getAlpha"), jint>(); }
inline void BitmapDrawable::setColorFilter(ref<android::graphics::ColorFilter> colorFilter) { return call_method<SCAPIX_META_STRING("setColorFilter"), void>(colorFilter); }
inline ref<android::graphics::ColorFilter> BitmapDrawable::getColorFilter() { return call_method<SCAPIX_META_STRING("getColorFilter"), ref<android::graphics::ColorFilter>>(); }
inline void BitmapDrawable::setTintList(ref<android::content::res::ColorStateList> tint) { return call_method<SCAPIX_META_STRING("setTintList"), void>(tint); }
inline void BitmapDrawable::setTintMode(ref<android::graphics::PorterDuff_Mode> tintMode) { return call_method<SCAPIX_META_STRING("setTintMode"), void>(tintMode); }
inline ref<android::graphics::drawable::Drawable> BitmapDrawable::mutate() { return call_method<SCAPIX_META_STRING("mutate"), ref<android::graphics::drawable::Drawable>>(); }
inline jboolean BitmapDrawable::isStateful() { return call_method<SCAPIX_META_STRING("isStateful"), jboolean>(); }
inline void BitmapDrawable::inflate(ref<android::content::res::Resources> r, ref<org::xmlpull::v1::XmlPullParser> parser, ref<android::util::AttributeSet> attrs, ref<android::content::res::Resources_Theme> theme) { return call_method<SCAPIX_META_STRING("inflate"), void>(r, parser, attrs, theme); }
inline void BitmapDrawable::applyTheme(ref<android::content::res::Resources_Theme> t) { return call_method<SCAPIX_META_STRING("applyTheme"), void>(t); }
inline jboolean BitmapDrawable::canApplyTheme() { return call_method<SCAPIX_META_STRING("canApplyTheme"), jboolean>(); }
inline jint BitmapDrawable::getIntrinsicWidth() { return call_method<SCAPIX_META_STRING("getIntrinsicWidth"), jint>(); }
inline jint BitmapDrawable::getIntrinsicHeight() { return call_method<SCAPIX_META_STRING("getIntrinsicHeight"), jint>(); }
inline jint BitmapDrawable::getOpacity() { return call_method<SCAPIX_META_STRING("getOpacity"), jint>(); }
inline ref<android::graphics::drawable::Drawable_ConstantState> BitmapDrawable::getConstantState() { return call_method<SCAPIX_META_STRING("getConstantState"), ref<android::graphics::drawable::Drawable_ConstantState>>(); }

} // namespace android::graphics::drawable
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_GRAPHICS_DRAWABLE_BITMAPDRAWABLE_H
