// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/org/xml/sax/ContentHandler.h>

#ifndef SCAPIX_JAVAX_XML_TRANSFORM_SAX_TEMPLATESHANDLER_H
#define SCAPIX_JAVAX_XML_TRANSFORM_SAX_TEMPLATESHANDLER_H

namespace scapix::java_api {

namespace java::lang { class String; }
namespace javax::xml::transform { class Templates; }

namespace javax::xml::transform::sax {

class TemplatesHandler : public object_base<SCAPIX_META_STRING("javax/xml/transform/sax/TemplatesHandler"),
	java::lang::Object,
	org::xml::sax::ContentHandler>
{
public:

	ref<javax::xml::transform::Templates> getTemplates();
	void setSystemId(ref<java::lang::String> p1);
	ref<java::lang::String> getSystemId();

protected:

	TemplatesHandler(handle_type h) : base_(h) {}

};

} // namespace javax::xml::transform::sax
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/javax/xml/transform/Templates.h>

namespace scapix::java_api {
namespace javax::xml::transform::sax {

inline ref<javax::xml::transform::Templates> TemplatesHandler::getTemplates() { return call_method<SCAPIX_META_STRING("getTemplates"), ref<javax::xml::transform::Templates>>(); }
inline void TemplatesHandler::setSystemId(ref<java::lang::String> p1) { return call_method<SCAPIX_META_STRING("setSystemId"), void>(p1); }
inline ref<java::lang::String> TemplatesHandler::getSystemId() { return call_method<SCAPIX_META_STRING("getSystemId"), ref<java::lang::String>>(); }

} // namespace javax::xml::transform::sax
} // namespace scapix::java_api

#endif // SCAPIX_JAVAX_XML_TRANSFORM_SAX_TEMPLATESHANDLER_H
