// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/os/Parcelable.h>

#ifndef SCAPIX_ANDROID_CONTENT_PM_PACKAGESTATS_H
#define SCAPIX_ANDROID_CONTENT_PM_PACKAGESTATS_H

namespace scapix::java_api {

namespace android::os { class Parcel; }
namespace android::os { class Parcelable_Creator; }
namespace java::lang { class String; }

namespace android::content::pm {

class PackageStats : public object_base<SCAPIX_META_STRING("android/content/pm/PackageStats"),
	java::lang::Object,
	android::os::Parcelable>
{
public:

	static ref<android::os::Parcelable_Creator> CREATOR_();
	jlong cacheSize();
	void cacheSize(jlong);
	jlong codeSize();
	void codeSize(jlong);
	jlong dataSize();
	void dataSize(jlong);
	jlong externalCacheSize();
	void externalCacheSize(jlong);
	jlong externalCodeSize();
	void externalCodeSize(jlong);
	jlong externalDataSize();
	void externalDataSize(jlong);
	jlong externalMediaSize();
	void externalMediaSize(jlong);
	jlong externalObbSize();
	void externalObbSize(jlong);
	ref<java::lang::String> packageName();
	void packageName(ref<java::lang::String>);

	static ref<PackageStats> new_object(ref<java::lang::String> pkgName);
	static ref<PackageStats> new_object(ref<android::os::Parcel> source);
	static ref<PackageStats> new_object(ref<android::content::pm::PackageStats> pStats);
	ref<java::lang::String> toString();
	jint describeContents();
	void writeToParcel(ref<android::os::Parcel> dest, jint parcelableFlags);
	jboolean equals(ref<java::lang::Object> obj);
	jint hashCode();

protected:

	PackageStats(handle_type h) : base_(h) {}

};

} // namespace android::content::pm
} // namespace scapix::java_api

#include <scapix/java_api/android/os/Parcel.h>
#include <scapix/java_api/android/os/Parcelable_Creator.h>
#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::content::pm {

inline ref<android::os::Parcelable_Creator> PackageStats::CREATOR_() { return get_static_field<SCAPIX_META_STRING("CREATOR"), ref<android::os::Parcelable_Creator>>(); }
inline jlong PackageStats::cacheSize() { return get_field<SCAPIX_META_STRING("cacheSize"), jlong>(); }
inline void PackageStats::cacheSize(jlong v) { set_field<SCAPIX_META_STRING("cacheSize"), jlong>(v); }
inline jlong PackageStats::codeSize() { return get_field<SCAPIX_META_STRING("codeSize"), jlong>(); }
inline void PackageStats::codeSize(jlong v) { set_field<SCAPIX_META_STRING("codeSize"), jlong>(v); }
inline jlong PackageStats::dataSize() { return get_field<SCAPIX_META_STRING("dataSize"), jlong>(); }
inline void PackageStats::dataSize(jlong v) { set_field<SCAPIX_META_STRING("dataSize"), jlong>(v); }
inline jlong PackageStats::externalCacheSize() { return get_field<SCAPIX_META_STRING("externalCacheSize"), jlong>(); }
inline void PackageStats::externalCacheSize(jlong v) { set_field<SCAPIX_META_STRING("externalCacheSize"), jlong>(v); }
inline jlong PackageStats::externalCodeSize() { return get_field<SCAPIX_META_STRING("externalCodeSize"), jlong>(); }
inline void PackageStats::externalCodeSize(jlong v) { set_field<SCAPIX_META_STRING("externalCodeSize"), jlong>(v); }
inline jlong PackageStats::externalDataSize() { return get_field<SCAPIX_META_STRING("externalDataSize"), jlong>(); }
inline void PackageStats::externalDataSize(jlong v) { set_field<SCAPIX_META_STRING("externalDataSize"), jlong>(v); }
inline jlong PackageStats::externalMediaSize() { return get_field<SCAPIX_META_STRING("externalMediaSize"), jlong>(); }
inline void PackageStats::externalMediaSize(jlong v) { set_field<SCAPIX_META_STRING("externalMediaSize"), jlong>(v); }
inline jlong PackageStats::externalObbSize() { return get_field<SCAPIX_META_STRING("externalObbSize"), jlong>(); }
inline void PackageStats::externalObbSize(jlong v) { set_field<SCAPIX_META_STRING("externalObbSize"), jlong>(v); }
inline ref<java::lang::String> PackageStats::packageName() { return get_field<SCAPIX_META_STRING("packageName"), ref<java::lang::String>>(); }
inline void PackageStats::packageName(ref<java::lang::String> v) { set_field<SCAPIX_META_STRING("packageName"), ref<java::lang::String>>(v); }
inline ref<PackageStats> PackageStats::new_object(ref<java::lang::String> pkgName) { return base_::new_object(pkgName); }
inline ref<PackageStats> PackageStats::new_object(ref<android::os::Parcel> source) { return base_::new_object(source); }
inline ref<PackageStats> PackageStats::new_object(ref<android::content::pm::PackageStats> pStats) { return base_::new_object(pStats); }
inline ref<java::lang::String> PackageStats::toString() { return call_method<SCAPIX_META_STRING("toString"), ref<java::lang::String>>(); }
inline jint PackageStats::describeContents() { return call_method<SCAPIX_META_STRING("describeContents"), jint>(); }
inline void PackageStats::writeToParcel(ref<android::os::Parcel> dest, jint parcelableFlags) { return call_method<SCAPIX_META_STRING("writeToParcel"), void>(dest, parcelableFlags); }
inline jboolean PackageStats::equals(ref<java::lang::Object> obj) { return call_method<SCAPIX_META_STRING("equals"), jboolean>(obj); }
inline jint PackageStats::hashCode() { return call_method<SCAPIX_META_STRING("hashCode"), jint>(); }

} // namespace android::content::pm
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_CONTENT_PM_PACKAGESTATS_H
