// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_TELEPHONY_CELLSIGNALSTRENGTH_H
#define SCAPIX_ANDROID_TELEPHONY_CELLSIGNALSTRENGTH_H

namespace scapix::java_api {
namespace android::telephony {

class CellSignalStrength : public object_base<SCAPIX_META_STRING("android/telephony/CellSignalStrength"),
	java::lang::Object>
{
public:

	static jint SIGNAL_STRENGTH_GOOD_();
	static jint SIGNAL_STRENGTH_GREAT_();
	static jint SIGNAL_STRENGTH_MODERATE_();
	static jint SIGNAL_STRENGTH_NONE_OR_UNKNOWN_();
	static jint SIGNAL_STRENGTH_POOR_();

	jint getLevel();
	jint getAsuLevel();
	jint getDbm();
	jint hashCode();
	jboolean equals(ref<java::lang::Object> p1);

protected:

	CellSignalStrength(handle_type h) : base_(h) {}

};

} // namespace android::telephony
} // namespace scapix::java_api


namespace scapix::java_api {
namespace android::telephony {

inline jint CellSignalStrength::SIGNAL_STRENGTH_GOOD_() { return get_static_field<SCAPIX_META_STRING("SIGNAL_STRENGTH_GOOD"), jint>(); }
inline jint CellSignalStrength::SIGNAL_STRENGTH_GREAT_() { return get_static_field<SCAPIX_META_STRING("SIGNAL_STRENGTH_GREAT"), jint>(); }
inline jint CellSignalStrength::SIGNAL_STRENGTH_MODERATE_() { return get_static_field<SCAPIX_META_STRING("SIGNAL_STRENGTH_MODERATE"), jint>(); }
inline jint CellSignalStrength::SIGNAL_STRENGTH_NONE_OR_UNKNOWN_() { return get_static_field<SCAPIX_META_STRING("SIGNAL_STRENGTH_NONE_OR_UNKNOWN"), jint>(); }
inline jint CellSignalStrength::SIGNAL_STRENGTH_POOR_() { return get_static_field<SCAPIX_META_STRING("SIGNAL_STRENGTH_POOR"), jint>(); }
inline jint CellSignalStrength::getLevel() { return call_method<SCAPIX_META_STRING("getLevel"), jint>(); }
inline jint CellSignalStrength::getAsuLevel() { return call_method<SCAPIX_META_STRING("getAsuLevel"), jint>(); }
inline jint CellSignalStrength::getDbm() { return call_method<SCAPIX_META_STRING("getDbm"), jint>(); }
inline jint CellSignalStrength::hashCode() { return call_method<SCAPIX_META_STRING("hashCode"), jint>(); }
inline jboolean CellSignalStrength::equals(ref<java::lang::Object> p1) { return call_method<SCAPIX_META_STRING("equals"), jboolean>(p1); }

} // namespace android::telephony
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_TELEPHONY_CELLSIGNALSTRENGTH_H
