// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>
#include <scapix/java_api/android/os/Parcelable.h>

#ifndef SCAPIX_ANDROID_TELEPHONY_RADIOACCESSSPECIFIER_H
#define SCAPIX_ANDROID_TELEPHONY_RADIOACCESSSPECIFIER_H

namespace scapix::java_api {

namespace android::os { class Parcel; }
namespace android::os { class Parcelable_Creator; }

namespace android::telephony {

class RadioAccessSpecifier : public object_base<SCAPIX_META_STRING("android/telephony/RadioAccessSpecifier"),
	java::lang::Object,
	android::os::Parcelable>
{
public:

	static ref<android::os::Parcelable_Creator> CREATOR_();

	static ref<RadioAccessSpecifier> new_object(jint ran, ref<link::java::array<jint>> bands, ref<link::java::array<jint>> channels);
	jint getRadioAccessNetwork();
	ref<link::java::array<jint>> getBands();
	ref<link::java::array<jint>> getChannels();
	jint describeContents();
	void writeToParcel(ref<android::os::Parcel> dest, jint flags);
	jboolean equals(ref<java::lang::Object> o);
	jint hashCode();

protected:

	RadioAccessSpecifier(handle_type h) : base_(h) {}

};

} // namespace android::telephony
} // namespace scapix::java_api

#include <scapix/java_api/android/os/Parcel.h>
#include <scapix/java_api/android/os/Parcelable_Creator.h>

namespace scapix::java_api {
namespace android::telephony {

inline ref<android::os::Parcelable_Creator> RadioAccessSpecifier::CREATOR_() { return get_static_field<SCAPIX_META_STRING("CREATOR"), ref<android::os::Parcelable_Creator>>(); }
inline ref<RadioAccessSpecifier> RadioAccessSpecifier::new_object(jint ran, ref<link::java::array<jint>> bands, ref<link::java::array<jint>> channels) { return base_::new_object(ran, bands, channels); }
inline jint RadioAccessSpecifier::getRadioAccessNetwork() { return call_method<SCAPIX_META_STRING("getRadioAccessNetwork"), jint>(); }
inline ref<link::java::array<jint>> RadioAccessSpecifier::getBands() { return call_method<SCAPIX_META_STRING("getBands"), ref<link::java::array<jint>>>(); }
inline ref<link::java::array<jint>> RadioAccessSpecifier::getChannels() { return call_method<SCAPIX_META_STRING("getChannels"), ref<link::java::array<jint>>>(); }
inline jint RadioAccessSpecifier::describeContents() { return call_method<SCAPIX_META_STRING("describeContents"), jint>(); }
inline void RadioAccessSpecifier::writeToParcel(ref<android::os::Parcel> dest, jint flags) { return call_method<SCAPIX_META_STRING("writeToParcel"), void>(dest, flags); }
inline jboolean RadioAccessSpecifier::equals(ref<java::lang::Object> o) { return call_method<SCAPIX_META_STRING("equals"), jboolean>(o); }
inline jint RadioAccessSpecifier::hashCode() { return call_method<SCAPIX_META_STRING("hashCode"), jint>(); }

} // namespace android::telephony
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_TELEPHONY_RADIOACCESSSPECIFIER_H
