// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_MEDIA_AUDIOFX_PRESETREVERB_ONPARAMETERCHANGELISTENER_H
#define SCAPIX_ANDROID_MEDIA_AUDIOFX_PRESETREVERB_ONPARAMETERCHANGELISTENER_H

namespace scapix::java_api {

namespace android::media::audiofx { class PresetReverb; }

namespace android::media::audiofx {

class PresetReverb_OnParameterChangeListener : public object_base<SCAPIX_META_STRING("android/media/audiofx/PresetReverb$OnParameterChangeListener"),
	java::lang::Object>
{
public:

	void onParameterChange(ref<android::media::audiofx::PresetReverb> p1, jint p2, jint p3, jshort p4);

protected:

	PresetReverb_OnParameterChangeListener(handle_type h) : base_(h) {}

};

} // namespace android::media::audiofx
} // namespace scapix::java_api

#include <scapix/java_api/android/media/audiofx/PresetReverb.h>

namespace scapix::java_api {
namespace android::media::audiofx {

inline void PresetReverb_OnParameterChangeListener::onParameterChange(ref<android::media::audiofx::PresetReverb> p1, jint p2, jint p3, jshort p4) { return call_method<SCAPIX_META_STRING("onParameterChange"), void>(p1, p2, p3, p4); }

} // namespace android::media::audiofx
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_MEDIA_AUDIOFX_PRESETREVERB_ONPARAMETERCHANGELISTENER_H
