// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_MEDIA_SESSION_MEDIASESSIONMANAGER_ONACTIVESESSIONSCHANGEDLISTENER_H
#define SCAPIX_ANDROID_MEDIA_SESSION_MEDIASESSIONMANAGER_ONACTIVESESSIONSCHANGEDLISTENER_H

namespace scapix::java_api {

namespace java::util { class List; }

namespace android::media::session {

class MediaSessionManager_OnActiveSessionsChangedListener : public object_base<SCAPIX_META_STRING("android/media/session/MediaSessionManager$OnActiveSessionsChangedListener"),
	java::lang::Object>
{
public:

	void onActiveSessionsChanged(ref<java::util::List> p1);

protected:

	MediaSessionManager_OnActiveSessionsChangedListener(handle_type h) : base_(h) {}

};

} // namespace android::media::session
} // namespace scapix::java_api

#include <scapix/java_api/java/util/List.h>

namespace scapix::java_api {
namespace android::media::session {

inline void MediaSessionManager_OnActiveSessionsChangedListener::onActiveSessionsChanged(ref<java::util::List> p1) { return call_method<SCAPIX_META_STRING("onActiveSessionsChanged"), void>(p1); }

} // namespace android::media::session
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_MEDIA_SESSION_MEDIASESSIONMANAGER_ONACTIVESESSIONSCHANGEDLISTENER_H
