// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_PROVIDER_CALENDARCONTRACT_CALENDARALERTSCOLUMNS_H
#define SCAPIX_ANDROID_PROVIDER_CALENDARCONTRACT_CALENDARALERTSCOLUMNS_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace android::provider {

class CalendarContract_CalendarAlertsColumns : public object_base<SCAPIX_META_STRING("android/provider/CalendarContract$CalendarAlertsColumns"),
	java::lang::Object>
{
public:

	static ref<java::lang::String> ALARM_TIME_();
	static ref<java::lang::String> BEGIN_();
	static ref<java::lang::String> CREATION_TIME_();
	static ref<java::lang::String> DEFAULT_SORT_ORDER_();
	static ref<java::lang::String> END_();
	static ref<java::lang::String> EVENT_ID_();
	static ref<java::lang::String> MINUTES_();
	static ref<java::lang::String> NOTIFY_TIME_();
	static ref<java::lang::String> RECEIVED_TIME_();
	static ref<java::lang::String> STATE_();
	static jint STATE_DISMISSED_();
	static jint STATE_FIRED_();
	static jint STATE_SCHEDULED_();


protected:

	CalendarContract_CalendarAlertsColumns(handle_type h) : base_(h) {}

};

} // namespace android::provider
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::provider {

inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::ALARM_TIME_() { return get_static_field<SCAPIX_META_STRING("ALARM_TIME"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::BEGIN_() { return get_static_field<SCAPIX_META_STRING("BEGIN"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::CREATION_TIME_() { return get_static_field<SCAPIX_META_STRING("CREATION_TIME"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::DEFAULT_SORT_ORDER_() { return get_static_field<SCAPIX_META_STRING("DEFAULT_SORT_ORDER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::END_() { return get_static_field<SCAPIX_META_STRING("END"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::EVENT_ID_() { return get_static_field<SCAPIX_META_STRING("EVENT_ID"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::MINUTES_() { return get_static_field<SCAPIX_META_STRING("MINUTES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::NOTIFY_TIME_() { return get_static_field<SCAPIX_META_STRING("NOTIFY_TIME"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::RECEIVED_TIME_() { return get_static_field<SCAPIX_META_STRING("RECEIVED_TIME"), ref<java::lang::String>>(); }
inline ref<java::lang::String> CalendarContract_CalendarAlertsColumns::STATE_() { return get_static_field<SCAPIX_META_STRING("STATE"), ref<java::lang::String>>(); }
inline jint CalendarContract_CalendarAlertsColumns::STATE_DISMISSED_() { return get_static_field<SCAPIX_META_STRING("STATE_DISMISSED"), jint>(); }
inline jint CalendarContract_CalendarAlertsColumns::STATE_FIRED_() { return get_static_field<SCAPIX_META_STRING("STATE_FIRED"), jint>(); }
inline jint CalendarContract_CalendarAlertsColumns::STATE_SCHEDULED_() { return get_static_field<SCAPIX_META_STRING("STATE_SCHEDULED"), jint>(); }

} // namespace android::provider
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_PROVIDER_CALENDARCONTRACT_CALENDARALERTSCOLUMNS_H
