// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_TEXT_BIDIFORMATTER_BUILDER_H
#define SCAPIX_ANDROID_TEXT_BIDIFORMATTER_BUILDER_H

namespace scapix::java_api {

namespace android::text { class BidiFormatter; }
namespace android::text { class TextDirectionHeuristic; }
namespace java::util { class Locale; }

namespace android::text {

class BidiFormatter_Builder : public object_base<SCAPIX_META_STRING("android/text/BidiFormatter$Builder"),
	java::lang::Object>
{
public:

	static ref<BidiFormatter_Builder> new_object();
	static ref<BidiFormatter_Builder> new_object(jboolean rtlContext);
	static ref<BidiFormatter_Builder> new_object(ref<java::util::Locale> locale);
	ref<android::text::BidiFormatter_Builder> stereoReset(jboolean stereoReset);
	ref<android::text::BidiFormatter_Builder> setTextDirectionHeuristic(ref<android::text::TextDirectionHeuristic> heuristic);
	ref<android::text::BidiFormatter> build();

protected:

	BidiFormatter_Builder(handle_type h) : base_(h) {}

};

} // namespace android::text
} // namespace scapix::java_api

#include <scapix/java_api/android/text/BidiFormatter.h>
#include <scapix/java_api/android/text/TextDirectionHeuristic.h>
#include <scapix/java_api/java/util/Locale.h>

namespace scapix::java_api {
namespace android::text {

inline ref<BidiFormatter_Builder> BidiFormatter_Builder::new_object() { return base_::new_object(); }
inline ref<BidiFormatter_Builder> BidiFormatter_Builder::new_object(jboolean rtlContext) { return base_::new_object(rtlContext); }
inline ref<BidiFormatter_Builder> BidiFormatter_Builder::new_object(ref<java::util::Locale> locale) { return base_::new_object(locale); }
inline ref<android::text::BidiFormatter_Builder> BidiFormatter_Builder::stereoReset(jboolean stereoReset) { return call_method<SCAPIX_META_STRING("stereoReset"), ref<android::text::BidiFormatter_Builder>>(stereoReset); }
inline ref<android::text::BidiFormatter_Builder> BidiFormatter_Builder::setTextDirectionHeuristic(ref<android::text::TextDirectionHeuristic> heuristic) { return call_method<SCAPIX_META_STRING("setTextDirectionHeuristic"), ref<android::text::BidiFormatter_Builder>>(heuristic); }
inline ref<android::text::BidiFormatter> BidiFormatter_Builder::build() { return call_method<SCAPIX_META_STRING("build"), ref<android::text::BidiFormatter>>(); }

} // namespace android::text
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_TEXT_BIDIFORMATTER_BUILDER_H
