// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/text/Layout.h>

#ifndef SCAPIX_ANDROID_TEXT_DYNAMICLAYOUT_H
#define SCAPIX_ANDROID_TEXT_DYNAMICLAYOUT_H

namespace scapix::java_api {

namespace android::text { class Layout_Alignment; }
namespace android::text { class Layout_Directions; }
namespace android::text { class TextPaint; }
namespace android::text { class TextUtils_TruncateAt; }
namespace java::lang { class CharSequence; }
namespace android::text { class DynamicLayout_Builder; }

namespace android::text {

class DynamicLayout : public object_base<SCAPIX_META_STRING("android/text/DynamicLayout"),
	android::text::Layout>
{
public:

	using Builder = DynamicLayout_Builder;

	static ref<DynamicLayout> new_object(ref<java::lang::CharSequence> base, ref<android::text::TextPaint> paint, jint width, ref<android::text::Layout_Alignment> align, jfloat spacingmult, jfloat spacingadd, jboolean includepad);
	static ref<DynamicLayout> new_object(ref<java::lang::CharSequence> base, ref<java::lang::CharSequence> display, ref<android::text::TextPaint> paint, jint width, ref<android::text::Layout_Alignment> align, jfloat spacingmult, jfloat spacingadd, jboolean includepad);
	static ref<DynamicLayout> new_object(ref<java::lang::CharSequence> base, ref<java::lang::CharSequence> display, ref<android::text::TextPaint> paint, jint width, ref<android::text::Layout_Alignment> align, jfloat spacingmult, jfloat spacingadd, jboolean includepad, ref<android::text::TextUtils_TruncateAt> ellipsize, jint ellipsizedWidth);
	jint getLineCount();
	jint getLineTop(jint line);
	jint getLineDescent(jint line);
	jint getLineStart(jint line);
	jboolean getLineContainsTab(jint line);
	jint getParagraphDirection(jint line);
	ref<android::text::Layout_Directions> getLineDirections(jint line);
	jint getTopPadding();
	jint getBottomPadding();
	jint getEllipsizedWidth();
	jint getEllipsisStart(jint line);
	jint getEllipsisCount(jint line);

protected:

	DynamicLayout(handle_type h) : base_(h) {}

};

} // namespace android::text
} // namespace scapix::java_api

#include <scapix/java_api/android/text/Layout_Alignment.h>
#include <scapix/java_api/android/text/Layout_Directions.h>
#include <scapix/java_api/android/text/TextPaint.h>
#include <scapix/java_api/android/text/TextUtils_TruncateAt.h>
#include <scapix/java_api/java/lang/CharSequence.h>

namespace scapix::java_api {
namespace android::text {

inline ref<DynamicLayout> DynamicLayout::new_object(ref<java::lang::CharSequence> base, ref<android::text::TextPaint> paint, jint width, ref<android::text::Layout_Alignment> align, jfloat spacingmult, jfloat spacingadd, jboolean includepad) { return base_::new_object(base, paint, width, align, spacingmult, spacingadd, includepad); }
inline ref<DynamicLayout> DynamicLayout::new_object(ref<java::lang::CharSequence> base, ref<java::lang::CharSequence> display, ref<android::text::TextPaint> paint, jint width, ref<android::text::Layout_Alignment> align, jfloat spacingmult, jfloat spacingadd, jboolean includepad) { return base_::new_object(base, display, paint, width, align, spacingmult, spacingadd, includepad); }
inline ref<DynamicLayout> DynamicLayout::new_object(ref<java::lang::CharSequence> base, ref<java::lang::CharSequence> display, ref<android::text::TextPaint> paint, jint width, ref<android::text::Layout_Alignment> align, jfloat spacingmult, jfloat spacingadd, jboolean includepad, ref<android::text::TextUtils_TruncateAt> ellipsize, jint ellipsizedWidth) { return base_::new_object(base, display, paint, width, align, spacingmult, spacingadd, includepad, ellipsize, ellipsizedWidth); }
inline jint DynamicLayout::getLineCount() { return call_method<SCAPIX_META_STRING("getLineCount"), jint>(); }
inline jint DynamicLayout::getLineTop(jint line) { return call_method<SCAPIX_META_STRING("getLineTop"), jint>(line); }
inline jint DynamicLayout::getLineDescent(jint line) { return call_method<SCAPIX_META_STRING("getLineDescent"), jint>(line); }
inline jint DynamicLayout::getLineStart(jint line) { return call_method<SCAPIX_META_STRING("getLineStart"), jint>(line); }
inline jboolean DynamicLayout::getLineContainsTab(jint line) { return call_method<SCAPIX_META_STRING("getLineContainsTab"), jboolean>(line); }
inline jint DynamicLayout::getParagraphDirection(jint line) { return call_method<SCAPIX_META_STRING("getParagraphDirection"), jint>(line); }
inline ref<android::text::Layout_Directions> DynamicLayout::getLineDirections(jint line) { return call_method<SCAPIX_META_STRING("getLineDirections"), ref<android::text::Layout_Directions>>(line); }
inline jint DynamicLayout::getTopPadding() { return call_method<SCAPIX_META_STRING("getTopPadding"), jint>(); }
inline jint DynamicLayout::getBottomPadding() { return call_method<SCAPIX_META_STRING("getBottomPadding"), jint>(); }
inline jint DynamicLayout::getEllipsizedWidth() { return call_method<SCAPIX_META_STRING("getEllipsizedWidth"), jint>(); }
inline jint DynamicLayout::getEllipsisStart(jint line) { return call_method<SCAPIX_META_STRING("getEllipsisStart"), jint>(line); }
inline jint DynamicLayout::getEllipsisCount(jint line) { return call_method<SCAPIX_META_STRING("getEllipsisCount"), jint>(line); }

} // namespace android::text
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_TEXT_DYNAMICLAYOUT_H
