// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_MANIFEST_PERMISSION_H
#define SCAPIX_ANDROID_MANIFEST_PERMISSION_H

namespace scapix::java_api {

namespace java::lang { class String; }

namespace android {

class Manifest_permission : public object_base<SCAPIX_META_STRING("android/Manifest$permission"),
	java::lang::Object>
{
public:

	static ref<java::lang::String> ACCEPT_HANDOVER_();
	static ref<java::lang::String> ACCESS_CHECKIN_PROPERTIES_();
	static ref<java::lang::String> ACCESS_COARSE_LOCATION_();
	static ref<java::lang::String> ACCESS_FINE_LOCATION_();
	static ref<java::lang::String> ACCESS_LOCATION_EXTRA_COMMANDS_();
	static ref<java::lang::String> ACCESS_NETWORK_STATE_();
	static ref<java::lang::String> ACCESS_NOTIFICATION_POLICY_();
	static ref<java::lang::String> ACCESS_WIFI_STATE_();
	static ref<java::lang::String> ACCOUNT_MANAGER_();
	static ref<java::lang::String> ADD_VOICEMAIL_();
	static ref<java::lang::String> ANSWER_PHONE_CALLS_();
	static ref<java::lang::String> BATTERY_STATS_();
	static ref<java::lang::String> BIND_ACCESSIBILITY_SERVICE_();
	static ref<java::lang::String> BIND_APPWIDGET_();
	static ref<java::lang::String> BIND_AUTOFILL_SERVICE_();
	static ref<java::lang::String> BIND_CARRIER_MESSAGING_SERVICE_();
	static ref<java::lang::String> BIND_CARRIER_SERVICES_();
	static ref<java::lang::String> BIND_CHOOSER_TARGET_SERVICE_();
	static ref<java::lang::String> BIND_CONDITION_PROVIDER_SERVICE_();
	static ref<java::lang::String> BIND_DEVICE_ADMIN_();
	static ref<java::lang::String> BIND_DREAM_SERVICE_();
	static ref<java::lang::String> BIND_INCALL_SERVICE_();
	static ref<java::lang::String> BIND_INPUT_METHOD_();
	static ref<java::lang::String> BIND_MIDI_DEVICE_SERVICE_();
	static ref<java::lang::String> BIND_NFC_SERVICE_();
	static ref<java::lang::String> BIND_NOTIFICATION_LISTENER_SERVICE_();
	static ref<java::lang::String> BIND_PRINT_SERVICE_();
	static ref<java::lang::String> BIND_QUICK_SETTINGS_TILE_();
	static ref<java::lang::String> BIND_REMOTEVIEWS_();
	static ref<java::lang::String> BIND_SCREENING_SERVICE_();
	static ref<java::lang::String> BIND_TELECOM_CONNECTION_SERVICE_();
	static ref<java::lang::String> BIND_TEXT_SERVICE_();
	static ref<java::lang::String> BIND_TV_INPUT_();
	static ref<java::lang::String> BIND_VISUAL_VOICEMAIL_SERVICE_();
	static ref<java::lang::String> BIND_VOICE_INTERACTION_();
	static ref<java::lang::String> BIND_VPN_SERVICE_();
	static ref<java::lang::String> BIND_VR_LISTENER_SERVICE_();
	static ref<java::lang::String> BIND_WALLPAPER_();
	static ref<java::lang::String> BLUETOOTH_();
	static ref<java::lang::String> BLUETOOTH_ADMIN_();
	static ref<java::lang::String> BLUETOOTH_PRIVILEGED_();
	static ref<java::lang::String> BODY_SENSORS_();
	static ref<java::lang::String> BROADCAST_PACKAGE_REMOVED_();
	static ref<java::lang::String> BROADCAST_SMS_();
	static ref<java::lang::String> BROADCAST_STICKY_();
	static ref<java::lang::String> BROADCAST_WAP_PUSH_();
	static ref<java::lang::String> CALL_PHONE_();
	static ref<java::lang::String> CALL_PRIVILEGED_();
	static ref<java::lang::String> CAMERA_();
	static ref<java::lang::String> CAPTURE_AUDIO_OUTPUT_();
	static ref<java::lang::String> CAPTURE_SECURE_VIDEO_OUTPUT_();
	static ref<java::lang::String> CAPTURE_VIDEO_OUTPUT_();
	static ref<java::lang::String> CHANGE_COMPONENT_ENABLED_STATE_();
	static ref<java::lang::String> CHANGE_CONFIGURATION_();
	static ref<java::lang::String> CHANGE_NETWORK_STATE_();
	static ref<java::lang::String> CHANGE_WIFI_MULTICAST_STATE_();
	static ref<java::lang::String> CHANGE_WIFI_STATE_();
	static ref<java::lang::String> CLEAR_APP_CACHE_();
	static ref<java::lang::String> CONTROL_LOCATION_UPDATES_();
	static ref<java::lang::String> DELETE_CACHE_FILES_();
	static ref<java::lang::String> DELETE_PACKAGES_();
	static ref<java::lang::String> DIAGNOSTIC_();
	static ref<java::lang::String> DISABLE_KEYGUARD_();
	static ref<java::lang::String> DUMP_();
	static ref<java::lang::String> EXPAND_STATUS_BAR_();
	static ref<java::lang::String> FACTORY_TEST_();
	static ref<java::lang::String> FOREGROUND_SERVICE_();
	static ref<java::lang::String> GET_ACCOUNTS_();
	static ref<java::lang::String> GET_ACCOUNTS_PRIVILEGED_();
	static ref<java::lang::String> GET_PACKAGE_SIZE_();
	static ref<java::lang::String> GET_TASKS_();
	static ref<java::lang::String> GLOBAL_SEARCH_();
	static ref<java::lang::String> INSTALL_LOCATION_PROVIDER_();
	static ref<java::lang::String> INSTALL_PACKAGES_();
	static ref<java::lang::String> INSTALL_SHORTCUT_();
	static ref<java::lang::String> INSTANT_APP_FOREGROUND_SERVICE_();
	static ref<java::lang::String> INTERNET_();
	static ref<java::lang::String> KILL_BACKGROUND_PROCESSES_();
	static ref<java::lang::String> LOCATION_HARDWARE_();
	static ref<java::lang::String> MANAGE_DOCUMENTS_();
	static ref<java::lang::String> MANAGE_OWN_CALLS_();
	static ref<java::lang::String> MASTER_CLEAR_();
	static ref<java::lang::String> MEDIA_CONTENT_CONTROL_();
	static ref<java::lang::String> MODIFY_AUDIO_SETTINGS_();
	static ref<java::lang::String> MODIFY_PHONE_STATE_();
	static ref<java::lang::String> MOUNT_FORMAT_FILESYSTEMS_();
	static ref<java::lang::String> MOUNT_UNMOUNT_FILESYSTEMS_();
	static ref<java::lang::String> NFC_();
	static ref<java::lang::String> NFC_TRANSACTION_EVENT_();
	static ref<java::lang::String> PACKAGE_USAGE_STATS_();
	static ref<java::lang::String> PERSISTENT_ACTIVITY_();
	static ref<java::lang::String> PROCESS_OUTGOING_CALLS_();
	static ref<java::lang::String> READ_CALENDAR_();
	static ref<java::lang::String> READ_CALL_LOG_();
	static ref<java::lang::String> READ_CONTACTS_();
	static ref<java::lang::String> READ_EXTERNAL_STORAGE_();
	static ref<java::lang::String> READ_FRAME_BUFFER_();
	static ref<java::lang::String> READ_INPUT_STATE_();
	static ref<java::lang::String> READ_LOGS_();
	static ref<java::lang::String> READ_PHONE_NUMBERS_();
	static ref<java::lang::String> READ_PHONE_STATE_();
	static ref<java::lang::String> READ_SMS_();
	static ref<java::lang::String> READ_SYNC_SETTINGS_();
	static ref<java::lang::String> READ_SYNC_STATS_();
	static ref<java::lang::String> READ_VOICEMAIL_();
	static ref<java::lang::String> REBOOT_();
	static ref<java::lang::String> RECEIVE_BOOT_COMPLETED_();
	static ref<java::lang::String> RECEIVE_MMS_();
	static ref<java::lang::String> RECEIVE_SMS_();
	static ref<java::lang::String> RECEIVE_WAP_PUSH_();
	static ref<java::lang::String> RECORD_AUDIO_();
	static ref<java::lang::String> REORDER_TASKS_();
	static ref<java::lang::String> REQUEST_COMPANION_RUN_IN_BACKGROUND_();
	static ref<java::lang::String> REQUEST_COMPANION_USE_DATA_IN_BACKGROUND_();
	static ref<java::lang::String> REQUEST_DELETE_PACKAGES_();
	static ref<java::lang::String> REQUEST_IGNORE_BATTERY_OPTIMIZATIONS_();
	static ref<java::lang::String> REQUEST_INSTALL_PACKAGES_();
	static ref<java::lang::String> RESTART_PACKAGES_();
	static ref<java::lang::String> SEND_RESPOND_VIA_MESSAGE_();
	static ref<java::lang::String> SEND_SMS_();
	static ref<java::lang::String> SET_ALARM_();
	static ref<java::lang::String> SET_ALWAYS_FINISH_();
	static ref<java::lang::String> SET_ANIMATION_SCALE_();
	static ref<java::lang::String> SET_DEBUG_APP_();
	static ref<java::lang::String> SET_PREFERRED_APPLICATIONS_();
	static ref<java::lang::String> SET_PROCESS_LIMIT_();
	static ref<java::lang::String> SET_TIME_();
	static ref<java::lang::String> SET_TIME_ZONE_();
	static ref<java::lang::String> SET_WALLPAPER_();
	static ref<java::lang::String> SET_WALLPAPER_HINTS_();
	static ref<java::lang::String> SIGNAL_PERSISTENT_PROCESSES_();
	static ref<java::lang::String> STATUS_BAR_();
	static ref<java::lang::String> SYSTEM_ALERT_WINDOW_();
	static ref<java::lang::String> TRANSMIT_IR_();
	static ref<java::lang::String> UNINSTALL_SHORTCUT_();
	static ref<java::lang::String> UPDATE_DEVICE_STATS_();
	static ref<java::lang::String> USE_BIOMETRIC_();
	static ref<java::lang::String> USE_FINGERPRINT_();
	static ref<java::lang::String> USE_SIP_();
	static ref<java::lang::String> VIBRATE_();
	static ref<java::lang::String> WAKE_LOCK_();
	static ref<java::lang::String> WRITE_APN_SETTINGS_();
	static ref<java::lang::String> WRITE_CALENDAR_();
	static ref<java::lang::String> WRITE_CALL_LOG_();
	static ref<java::lang::String> WRITE_CONTACTS_();
	static ref<java::lang::String> WRITE_EXTERNAL_STORAGE_();
	static ref<java::lang::String> WRITE_GSERVICES_();
	static ref<java::lang::String> WRITE_SECURE_SETTINGS_();
	static ref<java::lang::String> WRITE_SETTINGS_();
	static ref<java::lang::String> WRITE_SYNC_SETTINGS_();
	static ref<java::lang::String> WRITE_VOICEMAIL_();

	static ref<Manifest_permission> new_object();

protected:

	Manifest_permission(handle_type h) : base_(h) {}

};

} // namespace android
} // namespace scapix::java_api

#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android {

inline ref<java::lang::String> Manifest_permission::ACCEPT_HANDOVER_() { return get_static_field<SCAPIX_META_STRING("ACCEPT_HANDOVER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_CHECKIN_PROPERTIES_() { return get_static_field<SCAPIX_META_STRING("ACCESS_CHECKIN_PROPERTIES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_COARSE_LOCATION_() { return get_static_field<SCAPIX_META_STRING("ACCESS_COARSE_LOCATION"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_FINE_LOCATION_() { return get_static_field<SCAPIX_META_STRING("ACCESS_FINE_LOCATION"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_LOCATION_EXTRA_COMMANDS_() { return get_static_field<SCAPIX_META_STRING("ACCESS_LOCATION_EXTRA_COMMANDS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_NETWORK_STATE_() { return get_static_field<SCAPIX_META_STRING("ACCESS_NETWORK_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_NOTIFICATION_POLICY_() { return get_static_field<SCAPIX_META_STRING("ACCESS_NOTIFICATION_POLICY"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCESS_WIFI_STATE_() { return get_static_field<SCAPIX_META_STRING("ACCESS_WIFI_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ACCOUNT_MANAGER_() { return get_static_field<SCAPIX_META_STRING("ACCOUNT_MANAGER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ADD_VOICEMAIL_() { return get_static_field<SCAPIX_META_STRING("ADD_VOICEMAIL"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::ANSWER_PHONE_CALLS_() { return get_static_field<SCAPIX_META_STRING("ANSWER_PHONE_CALLS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BATTERY_STATS_() { return get_static_field<SCAPIX_META_STRING("BATTERY_STATS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_ACCESSIBILITY_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_ACCESSIBILITY_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_APPWIDGET_() { return get_static_field<SCAPIX_META_STRING("BIND_APPWIDGET"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_AUTOFILL_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_AUTOFILL_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_CARRIER_MESSAGING_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_CARRIER_MESSAGING_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_CARRIER_SERVICES_() { return get_static_field<SCAPIX_META_STRING("BIND_CARRIER_SERVICES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_CHOOSER_TARGET_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_CHOOSER_TARGET_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_CONDITION_PROVIDER_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_CONDITION_PROVIDER_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_DEVICE_ADMIN_() { return get_static_field<SCAPIX_META_STRING("BIND_DEVICE_ADMIN"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_DREAM_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_DREAM_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_INCALL_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_INCALL_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_INPUT_METHOD_() { return get_static_field<SCAPIX_META_STRING("BIND_INPUT_METHOD"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_MIDI_DEVICE_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_MIDI_DEVICE_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_NFC_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_NFC_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_NOTIFICATION_LISTENER_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_NOTIFICATION_LISTENER_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_PRINT_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_PRINT_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_QUICK_SETTINGS_TILE_() { return get_static_field<SCAPIX_META_STRING("BIND_QUICK_SETTINGS_TILE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_REMOTEVIEWS_() { return get_static_field<SCAPIX_META_STRING("BIND_REMOTEVIEWS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_SCREENING_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_SCREENING_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_TELECOM_CONNECTION_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_TELECOM_CONNECTION_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_TEXT_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_TEXT_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_TV_INPUT_() { return get_static_field<SCAPIX_META_STRING("BIND_TV_INPUT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_VISUAL_VOICEMAIL_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_VISUAL_VOICEMAIL_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_VOICE_INTERACTION_() { return get_static_field<SCAPIX_META_STRING("BIND_VOICE_INTERACTION"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_VPN_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_VPN_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_VR_LISTENER_SERVICE_() { return get_static_field<SCAPIX_META_STRING("BIND_VR_LISTENER_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BIND_WALLPAPER_() { return get_static_field<SCAPIX_META_STRING("BIND_WALLPAPER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BLUETOOTH_() { return get_static_field<SCAPIX_META_STRING("BLUETOOTH"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BLUETOOTH_ADMIN_() { return get_static_field<SCAPIX_META_STRING("BLUETOOTH_ADMIN"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BLUETOOTH_PRIVILEGED_() { return get_static_field<SCAPIX_META_STRING("BLUETOOTH_PRIVILEGED"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BODY_SENSORS_() { return get_static_field<SCAPIX_META_STRING("BODY_SENSORS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BROADCAST_PACKAGE_REMOVED_() { return get_static_field<SCAPIX_META_STRING("BROADCAST_PACKAGE_REMOVED"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BROADCAST_SMS_() { return get_static_field<SCAPIX_META_STRING("BROADCAST_SMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BROADCAST_STICKY_() { return get_static_field<SCAPIX_META_STRING("BROADCAST_STICKY"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::BROADCAST_WAP_PUSH_() { return get_static_field<SCAPIX_META_STRING("BROADCAST_WAP_PUSH"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CALL_PHONE_() { return get_static_field<SCAPIX_META_STRING("CALL_PHONE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CALL_PRIVILEGED_() { return get_static_field<SCAPIX_META_STRING("CALL_PRIVILEGED"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CAMERA_() { return get_static_field<SCAPIX_META_STRING("CAMERA"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CAPTURE_AUDIO_OUTPUT_() { return get_static_field<SCAPIX_META_STRING("CAPTURE_AUDIO_OUTPUT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CAPTURE_SECURE_VIDEO_OUTPUT_() { return get_static_field<SCAPIX_META_STRING("CAPTURE_SECURE_VIDEO_OUTPUT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CAPTURE_VIDEO_OUTPUT_() { return get_static_field<SCAPIX_META_STRING("CAPTURE_VIDEO_OUTPUT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CHANGE_COMPONENT_ENABLED_STATE_() { return get_static_field<SCAPIX_META_STRING("CHANGE_COMPONENT_ENABLED_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CHANGE_CONFIGURATION_() { return get_static_field<SCAPIX_META_STRING("CHANGE_CONFIGURATION"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CHANGE_NETWORK_STATE_() { return get_static_field<SCAPIX_META_STRING("CHANGE_NETWORK_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CHANGE_WIFI_MULTICAST_STATE_() { return get_static_field<SCAPIX_META_STRING("CHANGE_WIFI_MULTICAST_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CHANGE_WIFI_STATE_() { return get_static_field<SCAPIX_META_STRING("CHANGE_WIFI_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CLEAR_APP_CACHE_() { return get_static_field<SCAPIX_META_STRING("CLEAR_APP_CACHE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::CONTROL_LOCATION_UPDATES_() { return get_static_field<SCAPIX_META_STRING("CONTROL_LOCATION_UPDATES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::DELETE_CACHE_FILES_() { return get_static_field<SCAPIX_META_STRING("DELETE_CACHE_FILES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::DELETE_PACKAGES_() { return get_static_field<SCAPIX_META_STRING("DELETE_PACKAGES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::DIAGNOSTIC_() { return get_static_field<SCAPIX_META_STRING("DIAGNOSTIC"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::DISABLE_KEYGUARD_() { return get_static_field<SCAPIX_META_STRING("DISABLE_KEYGUARD"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::DUMP_() { return get_static_field<SCAPIX_META_STRING("DUMP"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::EXPAND_STATUS_BAR_() { return get_static_field<SCAPIX_META_STRING("EXPAND_STATUS_BAR"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::FACTORY_TEST_() { return get_static_field<SCAPIX_META_STRING("FACTORY_TEST"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::FOREGROUND_SERVICE_() { return get_static_field<SCAPIX_META_STRING("FOREGROUND_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::GET_ACCOUNTS_() { return get_static_field<SCAPIX_META_STRING("GET_ACCOUNTS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::GET_ACCOUNTS_PRIVILEGED_() { return get_static_field<SCAPIX_META_STRING("GET_ACCOUNTS_PRIVILEGED"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::GET_PACKAGE_SIZE_() { return get_static_field<SCAPIX_META_STRING("GET_PACKAGE_SIZE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::GET_TASKS_() { return get_static_field<SCAPIX_META_STRING("GET_TASKS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::GLOBAL_SEARCH_() { return get_static_field<SCAPIX_META_STRING("GLOBAL_SEARCH"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::INSTALL_LOCATION_PROVIDER_() { return get_static_field<SCAPIX_META_STRING("INSTALL_LOCATION_PROVIDER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::INSTALL_PACKAGES_() { return get_static_field<SCAPIX_META_STRING("INSTALL_PACKAGES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::INSTALL_SHORTCUT_() { return get_static_field<SCAPIX_META_STRING("INSTALL_SHORTCUT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::INSTANT_APP_FOREGROUND_SERVICE_() { return get_static_field<SCAPIX_META_STRING("INSTANT_APP_FOREGROUND_SERVICE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::INTERNET_() { return get_static_field<SCAPIX_META_STRING("INTERNET"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::KILL_BACKGROUND_PROCESSES_() { return get_static_field<SCAPIX_META_STRING("KILL_BACKGROUND_PROCESSES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::LOCATION_HARDWARE_() { return get_static_field<SCAPIX_META_STRING("LOCATION_HARDWARE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MANAGE_DOCUMENTS_() { return get_static_field<SCAPIX_META_STRING("MANAGE_DOCUMENTS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MANAGE_OWN_CALLS_() { return get_static_field<SCAPIX_META_STRING("MANAGE_OWN_CALLS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MASTER_CLEAR_() { return get_static_field<SCAPIX_META_STRING("MASTER_CLEAR"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MEDIA_CONTENT_CONTROL_() { return get_static_field<SCAPIX_META_STRING("MEDIA_CONTENT_CONTROL"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MODIFY_AUDIO_SETTINGS_() { return get_static_field<SCAPIX_META_STRING("MODIFY_AUDIO_SETTINGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MODIFY_PHONE_STATE_() { return get_static_field<SCAPIX_META_STRING("MODIFY_PHONE_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MOUNT_FORMAT_FILESYSTEMS_() { return get_static_field<SCAPIX_META_STRING("MOUNT_FORMAT_FILESYSTEMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::MOUNT_UNMOUNT_FILESYSTEMS_() { return get_static_field<SCAPIX_META_STRING("MOUNT_UNMOUNT_FILESYSTEMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::NFC_() { return get_static_field<SCAPIX_META_STRING("NFC"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::NFC_TRANSACTION_EVENT_() { return get_static_field<SCAPIX_META_STRING("NFC_TRANSACTION_EVENT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::PACKAGE_USAGE_STATS_() { return get_static_field<SCAPIX_META_STRING("PACKAGE_USAGE_STATS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::PERSISTENT_ACTIVITY_() { return get_static_field<SCAPIX_META_STRING("PERSISTENT_ACTIVITY"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::PROCESS_OUTGOING_CALLS_() { return get_static_field<SCAPIX_META_STRING("PROCESS_OUTGOING_CALLS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_CALENDAR_() { return get_static_field<SCAPIX_META_STRING("READ_CALENDAR"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_CALL_LOG_() { return get_static_field<SCAPIX_META_STRING("READ_CALL_LOG"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_CONTACTS_() { return get_static_field<SCAPIX_META_STRING("READ_CONTACTS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_EXTERNAL_STORAGE_() { return get_static_field<SCAPIX_META_STRING("READ_EXTERNAL_STORAGE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_FRAME_BUFFER_() { return get_static_field<SCAPIX_META_STRING("READ_FRAME_BUFFER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_INPUT_STATE_() { return get_static_field<SCAPIX_META_STRING("READ_INPUT_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_LOGS_() { return get_static_field<SCAPIX_META_STRING("READ_LOGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_PHONE_NUMBERS_() { return get_static_field<SCAPIX_META_STRING("READ_PHONE_NUMBERS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_PHONE_STATE_() { return get_static_field<SCAPIX_META_STRING("READ_PHONE_STATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_SMS_() { return get_static_field<SCAPIX_META_STRING("READ_SMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_SYNC_SETTINGS_() { return get_static_field<SCAPIX_META_STRING("READ_SYNC_SETTINGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_SYNC_STATS_() { return get_static_field<SCAPIX_META_STRING("READ_SYNC_STATS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::READ_VOICEMAIL_() { return get_static_field<SCAPIX_META_STRING("READ_VOICEMAIL"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REBOOT_() { return get_static_field<SCAPIX_META_STRING("REBOOT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::RECEIVE_BOOT_COMPLETED_() { return get_static_field<SCAPIX_META_STRING("RECEIVE_BOOT_COMPLETED"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::RECEIVE_MMS_() { return get_static_field<SCAPIX_META_STRING("RECEIVE_MMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::RECEIVE_SMS_() { return get_static_field<SCAPIX_META_STRING("RECEIVE_SMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::RECEIVE_WAP_PUSH_() { return get_static_field<SCAPIX_META_STRING("RECEIVE_WAP_PUSH"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::RECORD_AUDIO_() { return get_static_field<SCAPIX_META_STRING("RECORD_AUDIO"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REORDER_TASKS_() { return get_static_field<SCAPIX_META_STRING("REORDER_TASKS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REQUEST_COMPANION_RUN_IN_BACKGROUND_() { return get_static_field<SCAPIX_META_STRING("REQUEST_COMPANION_RUN_IN_BACKGROUND"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REQUEST_COMPANION_USE_DATA_IN_BACKGROUND_() { return get_static_field<SCAPIX_META_STRING("REQUEST_COMPANION_USE_DATA_IN_BACKGROUND"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REQUEST_DELETE_PACKAGES_() { return get_static_field<SCAPIX_META_STRING("REQUEST_DELETE_PACKAGES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REQUEST_IGNORE_BATTERY_OPTIMIZATIONS_() { return get_static_field<SCAPIX_META_STRING("REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::REQUEST_INSTALL_PACKAGES_() { return get_static_field<SCAPIX_META_STRING("REQUEST_INSTALL_PACKAGES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::RESTART_PACKAGES_() { return get_static_field<SCAPIX_META_STRING("RESTART_PACKAGES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SEND_RESPOND_VIA_MESSAGE_() { return get_static_field<SCAPIX_META_STRING("SEND_RESPOND_VIA_MESSAGE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SEND_SMS_() { return get_static_field<SCAPIX_META_STRING("SEND_SMS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_ALARM_() { return get_static_field<SCAPIX_META_STRING("SET_ALARM"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_ALWAYS_FINISH_() { return get_static_field<SCAPIX_META_STRING("SET_ALWAYS_FINISH"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_ANIMATION_SCALE_() { return get_static_field<SCAPIX_META_STRING("SET_ANIMATION_SCALE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_DEBUG_APP_() { return get_static_field<SCAPIX_META_STRING("SET_DEBUG_APP"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_PREFERRED_APPLICATIONS_() { return get_static_field<SCAPIX_META_STRING("SET_PREFERRED_APPLICATIONS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_PROCESS_LIMIT_() { return get_static_field<SCAPIX_META_STRING("SET_PROCESS_LIMIT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_TIME_() { return get_static_field<SCAPIX_META_STRING("SET_TIME"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_TIME_ZONE_() { return get_static_field<SCAPIX_META_STRING("SET_TIME_ZONE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_WALLPAPER_() { return get_static_field<SCAPIX_META_STRING("SET_WALLPAPER"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SET_WALLPAPER_HINTS_() { return get_static_field<SCAPIX_META_STRING("SET_WALLPAPER_HINTS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SIGNAL_PERSISTENT_PROCESSES_() { return get_static_field<SCAPIX_META_STRING("SIGNAL_PERSISTENT_PROCESSES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::STATUS_BAR_() { return get_static_field<SCAPIX_META_STRING("STATUS_BAR"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::SYSTEM_ALERT_WINDOW_() { return get_static_field<SCAPIX_META_STRING("SYSTEM_ALERT_WINDOW"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::TRANSMIT_IR_() { return get_static_field<SCAPIX_META_STRING("TRANSMIT_IR"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::UNINSTALL_SHORTCUT_() { return get_static_field<SCAPIX_META_STRING("UNINSTALL_SHORTCUT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::UPDATE_DEVICE_STATS_() { return get_static_field<SCAPIX_META_STRING("UPDATE_DEVICE_STATS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::USE_BIOMETRIC_() { return get_static_field<SCAPIX_META_STRING("USE_BIOMETRIC"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::USE_FINGERPRINT_() { return get_static_field<SCAPIX_META_STRING("USE_FINGERPRINT"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::USE_SIP_() { return get_static_field<SCAPIX_META_STRING("USE_SIP"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::VIBRATE_() { return get_static_field<SCAPIX_META_STRING("VIBRATE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WAKE_LOCK_() { return get_static_field<SCAPIX_META_STRING("WAKE_LOCK"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_APN_SETTINGS_() { return get_static_field<SCAPIX_META_STRING("WRITE_APN_SETTINGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_CALENDAR_() { return get_static_field<SCAPIX_META_STRING("WRITE_CALENDAR"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_CALL_LOG_() { return get_static_field<SCAPIX_META_STRING("WRITE_CALL_LOG"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_CONTACTS_() { return get_static_field<SCAPIX_META_STRING("WRITE_CONTACTS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_EXTERNAL_STORAGE_() { return get_static_field<SCAPIX_META_STRING("WRITE_EXTERNAL_STORAGE"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_GSERVICES_() { return get_static_field<SCAPIX_META_STRING("WRITE_GSERVICES"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_SECURE_SETTINGS_() { return get_static_field<SCAPIX_META_STRING("WRITE_SECURE_SETTINGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_SETTINGS_() { return get_static_field<SCAPIX_META_STRING("WRITE_SETTINGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_SYNC_SETTINGS_() { return get_static_field<SCAPIX_META_STRING("WRITE_SYNC_SETTINGS"), ref<java::lang::String>>(); }
inline ref<java::lang::String> Manifest_permission::WRITE_VOICEMAIL_() { return get_static_field<SCAPIX_META_STRING("WRITE_VOICEMAIL"), ref<java::lang::String>>(); }
inline ref<Manifest_permission> Manifest_permission::new_object() { return base_::new_object(); }

} // namespace android
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_MANIFEST_PERMISSION_H
