// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_MANIFEST_H
#define SCAPIX_ANDROID_MANIFEST_H

namespace scapix::java_api {

namespace android { class Manifest_permission_group; }
namespace android { class Manifest_permission; }

namespace android {

class Manifest : public object_base<SCAPIX_META_STRING("android/Manifest"),
	java::lang::Object>
{
public:

	using permission_group = Manifest_permission_group;
	using permission = Manifest_permission;

	static ref<Manifest> new_object();

protected:

	Manifest(handle_type h) : base_(h) {}

};

} // namespace android
} // namespace scapix::java_api


namespace scapix::java_api {
namespace android {

inline ref<Manifest> Manifest::new_object() { return base_::new_object(); }

} // namespace android
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_MANIFEST_H
