// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_R_ID_H
#define SCAPIX_ANDROID_R_ID_H

namespace scapix::java_api {


namespace android {

class R_id : public object_base<SCAPIX_META_STRING("android/R$id"),
	java::lang::Object>
{
public:

	static jint accessibilityActionContextClick();
	static jint accessibilityActionHideTooltip();
	static jint accessibilityActionMoveWindow();
	static jint accessibilityActionScrollDown();
	static jint accessibilityActionScrollLeft();
	static jint accessibilityActionScrollRight();
	static jint accessibilityActionScrollToPosition();
	static jint accessibilityActionScrollUp();
	static jint accessibilityActionSetProgress();
	static jint accessibilityActionShowOnScreen();
	static jint accessibilityActionShowTooltip();
	static jint addToDictionary();
	static jint autofill();
	static jint background();
	static jint button1();
	static jint button2();
	static jint button3();
	static jint candidatesArea();
	static jint checkbox();
	static jint closeButton();
	static jint content();
	static jint copy();
	static jint copyUrl();
	static jint custom();
	static jint cut();
	static jint edit();
	static jint empty();
	static jint extractArea();
	static jint hint();
	static jint home();
	static jint icon();
	static jint icon1();
	static jint icon2();
	static jint icon_frame();
	static jint input();
	static jint inputArea();
	static jint inputExtractEditText();
	static jint keyboardView();
	static jint list();
	static jint list_container();
	static jint mask();
	static jint message();
	static jint navigationBarBackground();
	static jint paste();
	static jint pasteAsPlainText();
	static jint primary();
	static jint progress();
	static jint redo();
	static jint replaceText();
	static jint secondaryProgress();
	static jint selectAll();
	static jint selectTextMode();
	static jint selectedIcon();
	static jint shareText();
	static jint startSelectingText();
	static jint statusBarBackground();
	static jint stopSelectingText();
	static jint summary();
	static jint switchInputMethod();
	static jint switch_widget();
	static jint tabcontent();
	static jint tabhost();
	static jint tabs();
	static jint text1();
	static jint text2();
	static jint textAssist();
	static jint title();
	static jint toggle();
	static jint undo();
	static jint widget_frame();

	static ref<R_id> new_object();

protected:

	R_id(handle_type h) : base_(h) {}

};

} // namespace android
} // namespace scapix::java_api


namespace scapix::java_api {
namespace android {

inline jint R_id::accessibilityActionContextClick() { return get_static_field<SCAPIX_META_STRING("accessibilityActionContextClick"), jint>(); }
inline jint R_id::accessibilityActionHideTooltip() { return get_static_field<SCAPIX_META_STRING("accessibilityActionHideTooltip"), jint>(); }
inline jint R_id::accessibilityActionMoveWindow() { return get_static_field<SCAPIX_META_STRING("accessibilityActionMoveWindow"), jint>(); }
inline jint R_id::accessibilityActionScrollDown() { return get_static_field<SCAPIX_META_STRING("accessibilityActionScrollDown"), jint>(); }
inline jint R_id::accessibilityActionScrollLeft() { return get_static_field<SCAPIX_META_STRING("accessibilityActionScrollLeft"), jint>(); }
inline jint R_id::accessibilityActionScrollRight() { return get_static_field<SCAPIX_META_STRING("accessibilityActionScrollRight"), jint>(); }
inline jint R_id::accessibilityActionScrollToPosition() { return get_static_field<SCAPIX_META_STRING("accessibilityActionScrollToPosition"), jint>(); }
inline jint R_id::accessibilityActionScrollUp() { return get_static_field<SCAPIX_META_STRING("accessibilityActionScrollUp"), jint>(); }
inline jint R_id::accessibilityActionSetProgress() { return get_static_field<SCAPIX_META_STRING("accessibilityActionSetProgress"), jint>(); }
inline jint R_id::accessibilityActionShowOnScreen() { return get_static_field<SCAPIX_META_STRING("accessibilityActionShowOnScreen"), jint>(); }
inline jint R_id::accessibilityActionShowTooltip() { return get_static_field<SCAPIX_META_STRING("accessibilityActionShowTooltip"), jint>(); }
inline jint R_id::addToDictionary() { return get_static_field<SCAPIX_META_STRING("addToDictionary"), jint>(); }
inline jint R_id::autofill() { return get_static_field<SCAPIX_META_STRING("autofill"), jint>(); }
inline jint R_id::background() { return get_static_field<SCAPIX_META_STRING("background"), jint>(); }
inline jint R_id::button1() { return get_static_field<SCAPIX_META_STRING("button1"), jint>(); }
inline jint R_id::button2() { return get_static_field<SCAPIX_META_STRING("button2"), jint>(); }
inline jint R_id::button3() { return get_static_field<SCAPIX_META_STRING("button3"), jint>(); }
inline jint R_id::candidatesArea() { return get_static_field<SCAPIX_META_STRING("candidatesArea"), jint>(); }
inline jint R_id::checkbox() { return get_static_field<SCAPIX_META_STRING("checkbox"), jint>(); }
inline jint R_id::closeButton() { return get_static_field<SCAPIX_META_STRING("closeButton"), jint>(); }
inline jint R_id::content() { return get_static_field<SCAPIX_META_STRING("content"), jint>(); }
inline jint R_id::copy() { return get_static_field<SCAPIX_META_STRING("copy"), jint>(); }
inline jint R_id::copyUrl() { return get_static_field<SCAPIX_META_STRING("copyUrl"), jint>(); }
inline jint R_id::custom() { return get_static_field<SCAPIX_META_STRING("custom"), jint>(); }
inline jint R_id::cut() { return get_static_field<SCAPIX_META_STRING("cut"), jint>(); }
inline jint R_id::edit() { return get_static_field<SCAPIX_META_STRING("edit"), jint>(); }
inline jint R_id::empty() { return get_static_field<SCAPIX_META_STRING("empty"), jint>(); }
inline jint R_id::extractArea() { return get_static_field<SCAPIX_META_STRING("extractArea"), jint>(); }
inline jint R_id::hint() { return get_static_field<SCAPIX_META_STRING("hint"), jint>(); }
inline jint R_id::home() { return get_static_field<SCAPIX_META_STRING("home"), jint>(); }
inline jint R_id::icon() { return get_static_field<SCAPIX_META_STRING("icon"), jint>(); }
inline jint R_id::icon1() { return get_static_field<SCAPIX_META_STRING("icon1"), jint>(); }
inline jint R_id::icon2() { return get_static_field<SCAPIX_META_STRING("icon2"), jint>(); }
inline jint R_id::icon_frame() { return get_static_field<SCAPIX_META_STRING("icon_frame"), jint>(); }
inline jint R_id::input() { return get_static_field<SCAPIX_META_STRING("input"), jint>(); }
inline jint R_id::inputArea() { return get_static_field<SCAPIX_META_STRING("inputArea"), jint>(); }
inline jint R_id::inputExtractEditText() { return get_static_field<SCAPIX_META_STRING("inputExtractEditText"), jint>(); }
inline jint R_id::keyboardView() { return get_static_field<SCAPIX_META_STRING("keyboardView"), jint>(); }
inline jint R_id::list() { return get_static_field<SCAPIX_META_STRING("list"), jint>(); }
inline jint R_id::list_container() { return get_static_field<SCAPIX_META_STRING("list_container"), jint>(); }
inline jint R_id::mask() { return get_static_field<SCAPIX_META_STRING("mask"), jint>(); }
inline jint R_id::message() { return get_static_field<SCAPIX_META_STRING("message"), jint>(); }
inline jint R_id::navigationBarBackground() { return get_static_field<SCAPIX_META_STRING("navigationBarBackground"), jint>(); }
inline jint R_id::paste() { return get_static_field<SCAPIX_META_STRING("paste"), jint>(); }
inline jint R_id::pasteAsPlainText() { return get_static_field<SCAPIX_META_STRING("pasteAsPlainText"), jint>(); }
inline jint R_id::primary() { return get_static_field<SCAPIX_META_STRING("primary"), jint>(); }
inline jint R_id::progress() { return get_static_field<SCAPIX_META_STRING("progress"), jint>(); }
inline jint R_id::redo() { return get_static_field<SCAPIX_META_STRING("redo"), jint>(); }
inline jint R_id::replaceText() { return get_static_field<SCAPIX_META_STRING("replaceText"), jint>(); }
inline jint R_id::secondaryProgress() { return get_static_field<SCAPIX_META_STRING("secondaryProgress"), jint>(); }
inline jint R_id::selectAll() { return get_static_field<SCAPIX_META_STRING("selectAll"), jint>(); }
inline jint R_id::selectTextMode() { return get_static_field<SCAPIX_META_STRING("selectTextMode"), jint>(); }
inline jint R_id::selectedIcon() { return get_static_field<SCAPIX_META_STRING("selectedIcon"), jint>(); }
inline jint R_id::shareText() { return get_static_field<SCAPIX_META_STRING("shareText"), jint>(); }
inline jint R_id::startSelectingText() { return get_static_field<SCAPIX_META_STRING("startSelectingText"), jint>(); }
inline jint R_id::statusBarBackground() { return get_static_field<SCAPIX_META_STRING("statusBarBackground"), jint>(); }
inline jint R_id::stopSelectingText() { return get_static_field<SCAPIX_META_STRING("stopSelectingText"), jint>(); }
inline jint R_id::summary() { return get_static_field<SCAPIX_META_STRING("summary"), jint>(); }
inline jint R_id::switchInputMethod() { return get_static_field<SCAPIX_META_STRING("switchInputMethod"), jint>(); }
inline jint R_id::switch_widget() { return get_static_field<SCAPIX_META_STRING("switch_widget"), jint>(); }
inline jint R_id::tabcontent() { return get_static_field<SCAPIX_META_STRING("tabcontent"), jint>(); }
inline jint R_id::tabhost() { return get_static_field<SCAPIX_META_STRING("tabhost"), jint>(); }
inline jint R_id::tabs() { return get_static_field<SCAPIX_META_STRING("tabs"), jint>(); }
inline jint R_id::text1() { return get_static_field<SCAPIX_META_STRING("text1"), jint>(); }
inline jint R_id::text2() { return get_static_field<SCAPIX_META_STRING("text2"), jint>(); }
inline jint R_id::textAssist() { return get_static_field<SCAPIX_META_STRING("textAssist"), jint>(); }
inline jint R_id::title() { return get_static_field<SCAPIX_META_STRING("title"), jint>(); }
inline jint R_id::toggle() { return get_static_field<SCAPIX_META_STRING("toggle"), jint>(); }
inline jint R_id::undo() { return get_static_field<SCAPIX_META_STRING("undo"), jint>(); }
inline jint R_id::widget_frame() { return get_static_field<SCAPIX_META_STRING("widget_frame"), jint>(); }
inline ref<R_id> R_id::new_object() { return base_::new_object(); }

} // namespace android
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_R_ID_H
