// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_NET_WIFI_P2P_WIFIP2PMANAGER_DNSSDSERVICERESPONSELISTENER_H
#define SCAPIX_ANDROID_NET_WIFI_P2P_WIFIP2PMANAGER_DNSSDSERVICERESPONSELISTENER_H

namespace scapix::java_api {

namespace android::net::wifi::p2p { class WifiP2pDevice; }
namespace java::lang { class String; }

namespace android::net::wifi::p2p {

class WifiP2pManager_DnsSdServiceResponseListener : public object_base<SCAPIX_META_STRING("android/net/wifi/p2p/WifiP2pManager$DnsSdServiceResponseListener"),
	java::lang::Object>
{
public:

	void onDnsSdServiceAvailable(ref<java::lang::String> p1, ref<java::lang::String> p2, ref<android::net::wifi::p2p::WifiP2pDevice> p3);

protected:

	WifiP2pManager_DnsSdServiceResponseListener(handle_type h) : base_(h) {}

};

} // namespace android::net::wifi::p2p
} // namespace scapix::java_api

#include <scapix/java_api/android/net/wifi/p2p/WifiP2pDevice.h>
#include <scapix/java_api/java/lang/String.h>

namespace scapix::java_api {
namespace android::net::wifi::p2p {

inline void WifiP2pManager_DnsSdServiceResponseListener::onDnsSdServiceAvailable(ref<java::lang::String> p1, ref<java::lang::String> p2, ref<android::net::wifi::p2p::WifiP2pDevice> p3) { return call_method<SCAPIX_META_STRING("onDnsSdServiceAvailable"), void>(p1, p2, p3); }

} // namespace android::net::wifi::p2p
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_NET_WIFI_P2P_WIFIP2PMANAGER_DNSSDSERVICERESPONSELISTENER_H
