// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_VIEW_MENU_H
#define SCAPIX_ANDROID_VIEW_MENU_H

namespace scapix::java_api {

namespace android::content { class ComponentName; }
namespace android::content { class Intent; }
namespace android::view { class KeyEvent; }
namespace android::view { class MenuItem; }
namespace android::view { class SubMenu; }
namespace java::lang { class CharSequence; }

namespace android::view {

class Menu : public object_base<SCAPIX_META_STRING("android/view/Menu"),
	java::lang::Object>
{
public:

	static jint CATEGORY_ALTERNATIVE_();
	static jint CATEGORY_CONTAINER_();
	static jint CATEGORY_SECONDARY_();
	static jint CATEGORY_SYSTEM_();
	static jint FIRST_();
	static jint FLAG_ALWAYS_PERFORM_CLOSE_();
	static jint FLAG_APPEND_TO_GROUP_();
	static jint FLAG_PERFORM_NO_CLOSE_();
	static jint NONE_();
	static jint SUPPORTED_MODIFIERS_MASK_();

	ref<android::view::MenuItem> add(ref<java::lang::CharSequence> p1);
	ref<android::view::MenuItem> add(jint p1);
	ref<android::view::MenuItem> add(jint p1, jint p2, jint p3, ref<java::lang::CharSequence> p4);
	ref<android::view::MenuItem> add(jint p1, jint p2, jint p3, jint p4);
	ref<android::view::SubMenu> addSubMenu(ref<java::lang::CharSequence> p1);
	ref<android::view::SubMenu> addSubMenu(jint p1);
	ref<android::view::SubMenu> addSubMenu(jint p1, jint p2, jint p3, ref<java::lang::CharSequence> p4);
	ref<android::view::SubMenu> addSubMenu(jint p1, jint p2, jint p3, jint p4);
	jint addIntentOptions(jint p1, jint p2, jint p3, ref<android::content::ComponentName> p4, ref<link::java::array<android::content::Intent>> p5, ref<android::content::Intent> p6, jint p7, ref<link::java::array<android::view::MenuItem>> p8);
	void removeItem(jint p1);
	void removeGroup(jint p1);
	void clear();
	void setGroupCheckable(jint p1, jboolean p2, jboolean p3);
	void setGroupVisible(jint p1, jboolean p2);
	void setGroupEnabled(jint p1, jboolean p2);
	jboolean hasVisibleItems();
	ref<android::view::MenuItem> findItem(jint p1);
	jint size();
	ref<android::view::MenuItem> getItem(jint p1);
	void close();
	jboolean performShortcut(jint p1, ref<android::view::KeyEvent> p2, jint p3);
	jboolean isShortcutKey(jint p1, ref<android::view::KeyEvent> p2);
	jboolean performIdentifierAction(jint p1, jint p2);
	void setQwertyMode(jboolean p1);
	void setGroupDividerEnabled(jboolean groupDividerEnabled);

protected:

	Menu(handle_type h) : base_(h) {}

};

} // namespace android::view
} // namespace scapix::java_api

#include <scapix/java_api/android/content/ComponentName.h>
#include <scapix/java_api/android/content/Intent.h>
#include <scapix/java_api/android/view/KeyEvent.h>
#include <scapix/java_api/android/view/MenuItem.h>
#include <scapix/java_api/android/view/SubMenu.h>
#include <scapix/java_api/java/lang/CharSequence.h>

namespace scapix::java_api {
namespace android::view {

inline jint Menu::CATEGORY_ALTERNATIVE_() { return get_static_field<SCAPIX_META_STRING("CATEGORY_ALTERNATIVE"), jint>(); }
inline jint Menu::CATEGORY_CONTAINER_() { return get_static_field<SCAPIX_META_STRING("CATEGORY_CONTAINER"), jint>(); }
inline jint Menu::CATEGORY_SECONDARY_() { return get_static_field<SCAPIX_META_STRING("CATEGORY_SECONDARY"), jint>(); }
inline jint Menu::CATEGORY_SYSTEM_() { return get_static_field<SCAPIX_META_STRING("CATEGORY_SYSTEM"), jint>(); }
inline jint Menu::FIRST_() { return get_static_field<SCAPIX_META_STRING("FIRST"), jint>(); }
inline jint Menu::FLAG_ALWAYS_PERFORM_CLOSE_() { return get_static_field<SCAPIX_META_STRING("FLAG_ALWAYS_PERFORM_CLOSE"), jint>(); }
inline jint Menu::FLAG_APPEND_TO_GROUP_() { return get_static_field<SCAPIX_META_STRING("FLAG_APPEND_TO_GROUP"), jint>(); }
inline jint Menu::FLAG_PERFORM_NO_CLOSE_() { return get_static_field<SCAPIX_META_STRING("FLAG_PERFORM_NO_CLOSE"), jint>(); }
inline jint Menu::NONE_() { return get_static_field<SCAPIX_META_STRING("NONE"), jint>(); }
inline jint Menu::SUPPORTED_MODIFIERS_MASK_() { return get_static_field<SCAPIX_META_STRING("SUPPORTED_MODIFIERS_MASK"), jint>(); }
inline ref<android::view::MenuItem> Menu::add(ref<java::lang::CharSequence> p1) { return call_method<SCAPIX_META_STRING("add"), ref<android::view::MenuItem>>(p1); }
inline ref<android::view::MenuItem> Menu::add(jint p1) { return call_method<SCAPIX_META_STRING("add"), ref<android::view::MenuItem>>(p1); }
inline ref<android::view::MenuItem> Menu::add(jint p1, jint p2, jint p3, ref<java::lang::CharSequence> p4) { return call_method<SCAPIX_META_STRING("add"), ref<android::view::MenuItem>>(p1, p2, p3, p4); }
inline ref<android::view::MenuItem> Menu::add(jint p1, jint p2, jint p3, jint p4) { return call_method<SCAPIX_META_STRING("add"), ref<android::view::MenuItem>>(p1, p2, p3, p4); }
inline ref<android::view::SubMenu> Menu::addSubMenu(ref<java::lang::CharSequence> p1) { return call_method<SCAPIX_META_STRING("addSubMenu"), ref<android::view::SubMenu>>(p1); }
inline ref<android::view::SubMenu> Menu::addSubMenu(jint p1) { return call_method<SCAPIX_META_STRING("addSubMenu"), ref<android::view::SubMenu>>(p1); }
inline ref<android::view::SubMenu> Menu::addSubMenu(jint p1, jint p2, jint p3, ref<java::lang::CharSequence> p4) { return call_method<SCAPIX_META_STRING("addSubMenu"), ref<android::view::SubMenu>>(p1, p2, p3, p4); }
inline ref<android::view::SubMenu> Menu::addSubMenu(jint p1, jint p2, jint p3, jint p4) { return call_method<SCAPIX_META_STRING("addSubMenu"), ref<android::view::SubMenu>>(p1, p2, p3, p4); }
inline jint Menu::addIntentOptions(jint p1, jint p2, jint p3, ref<android::content::ComponentName> p4, ref<link::java::array<android::content::Intent>> p5, ref<android::content::Intent> p6, jint p7, ref<link::java::array<android::view::MenuItem>> p8) { return call_method<SCAPIX_META_STRING("addIntentOptions"), jint>(p1, p2, p3, p4, p5, p6, p7, p8); }
inline void Menu::removeItem(jint p1) { return call_method<SCAPIX_META_STRING("removeItem"), void>(p1); }
inline void Menu::removeGroup(jint p1) { return call_method<SCAPIX_META_STRING("removeGroup"), void>(p1); }
inline void Menu::clear() { return call_method<SCAPIX_META_STRING("clear"), void>(); }
inline void Menu::setGroupCheckable(jint p1, jboolean p2, jboolean p3) { return call_method<SCAPIX_META_STRING("setGroupCheckable"), void>(p1, p2, p3); }
inline void Menu::setGroupVisible(jint p1, jboolean p2) { return call_method<SCAPIX_META_STRING("setGroupVisible"), void>(p1, p2); }
inline void Menu::setGroupEnabled(jint p1, jboolean p2) { return call_method<SCAPIX_META_STRING("setGroupEnabled"), void>(p1, p2); }
inline jboolean Menu::hasVisibleItems() { return call_method<SCAPIX_META_STRING("hasVisibleItems"), jboolean>(); }
inline ref<android::view::MenuItem> Menu::findItem(jint p1) { return call_method<SCAPIX_META_STRING("findItem"), ref<android::view::MenuItem>>(p1); }
inline jint Menu::size() { return call_method<SCAPIX_META_STRING("size"), jint>(); }
inline ref<android::view::MenuItem> Menu::getItem(jint p1) { return call_method<SCAPIX_META_STRING("getItem"), ref<android::view::MenuItem>>(p1); }
inline void Menu::close() { return call_method<SCAPIX_META_STRING("close"), void>(); }
inline jboolean Menu::performShortcut(jint p1, ref<android::view::KeyEvent> p2, jint p3) { return call_method<SCAPIX_META_STRING("performShortcut"), jboolean>(p1, p2, p3); }
inline jboolean Menu::isShortcutKey(jint p1, ref<android::view::KeyEvent> p2) { return call_method<SCAPIX_META_STRING("isShortcutKey"), jboolean>(p1, p2); }
inline jboolean Menu::performIdentifierAction(jint p1, jint p2) { return call_method<SCAPIX_META_STRING("performIdentifierAction"), jboolean>(p1, p2); }
inline void Menu::setQwertyMode(jboolean p1) { return call_method<SCAPIX_META_STRING("setQwertyMode"), void>(p1); }
inline void Menu::setGroupDividerEnabled(jboolean groupDividerEnabled) { return call_method<SCAPIX_META_STRING("setGroupDividerEnabled"), void>(groupDividerEnabled); }

} // namespace android::view
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_VIEW_MENU_H
