// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_VIEW_VIEWMANAGER_H
#define SCAPIX_ANDROID_VIEW_VIEWMANAGER_H

namespace scapix::java_api {

namespace android::view { class View; }
namespace android::view { class ViewGroup_LayoutParams; }

namespace android::view {

class ViewManager : public object_base<SCAPIX_META_STRING("android/view/ViewManager"),
	java::lang::Object>
{
public:

	void addView(ref<android::view::View> p1, ref<android::view::ViewGroup_LayoutParams> p2);
	void updateViewLayout(ref<android::view::View> p1, ref<android::view::ViewGroup_LayoutParams> p2);
	void removeView(ref<android::view::View> p1);

protected:

	ViewManager(handle_type h) : base_(h) {}

};

} // namespace android::view
} // namespace scapix::java_api

#include <scapix/java_api/android/view/View.h>
#include <scapix/java_api/android/view/ViewGroup_LayoutParams.h>

namespace scapix::java_api {
namespace android::view {

inline void ViewManager::addView(ref<android::view::View> p1, ref<android::view::ViewGroup_LayoutParams> p2) { return call_method<SCAPIX_META_STRING("addView"), void>(p1, p2); }
inline void ViewManager::updateViewLayout(ref<android::view::View> p1, ref<android::view::ViewGroup_LayoutParams> p2) { return call_method<SCAPIX_META_STRING("updateViewLayout"), void>(p1, p2); }
inline void ViewManager::removeView(ref<android::view::View> p1) { return call_method<SCAPIX_META_STRING("removeView"), void>(p1); }

} // namespace android::view
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_VIEW_VIEWMANAGER_H
