// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/java/lang/Object.h>

#ifndef SCAPIX_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER_H
#define SCAPIX_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER_H

namespace scapix::java_api {

namespace android::view { class KeyEvent; }
namespace android::view { class View; }

namespace android::view {

class View_OnUnhandledKeyEventListener : public object_base<SCAPIX_META_STRING("android/view/View$OnUnhandledKeyEventListener"),
	java::lang::Object>
{
public:

	jboolean onUnhandledKeyEvent(ref<android::view::View> p1, ref<android::view::KeyEvent> p2);

protected:

	View_OnUnhandledKeyEventListener(handle_type h) : base_(h) {}

};

} // namespace android::view
} // namespace scapix::java_api

#include <scapix/java_api/android/view/KeyEvent.h>
#include <scapix/java_api/android/view/View.h>

namespace scapix::java_api {
namespace android::view {

inline jboolean View_OnUnhandledKeyEventListener::onUnhandledKeyEvent(ref<android::view::View> p1, ref<android::view::KeyEvent> p2) { return call_method<SCAPIX_META_STRING("onUnhandledKeyEvent"), jboolean>(p1, p2); }

} // namespace android::view
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_VIEW_VIEW_ONUNHANDLEDKEYEVENTLISTENER_H
