// Generated by Scapix Java API
// https://www.scapix.com

#include <scapix/java_api/android/icu/util/Calendar.h>

#ifndef SCAPIX_ANDROID_ICU_UTIL_ISLAMICCALENDAR_H
#define SCAPIX_ANDROID_ICU_UTIL_ISLAMICCALENDAR_H

namespace scapix::java_api {

namespace android::icu::util { class IslamicCalendar_CalculationType; }
namespace android::icu::util { class TimeZone; }
namespace android::icu::util { class ULocale; }
namespace java::lang { class String; }
namespace java::util { class Date; }
namespace java::util { class Locale; }

namespace android::icu::util {

class IslamicCalendar : public object_base<SCAPIX_META_STRING("android/icu/util/IslamicCalendar"),
	android::icu::util::Calendar>
{
public:

	using CalculationType = IslamicCalendar_CalculationType;

	static jint DHU_AL_HIJJAH_();
	static jint DHU_AL_QIDAH_();
	static jint JUMADA_1_();
	static jint JUMADA_2_();
	static jint MUHARRAM_();
	static jint RABI_1_();
	static jint RABI_2_();
	static jint RAJAB_();
	static jint RAMADAN_();
	static jint SAFAR_();
	static jint SHABAN_();
	static jint SHAWWAL_();

	static ref<IslamicCalendar> new_object();
	static ref<IslamicCalendar> new_object(ref<android::icu::util::TimeZone> zone);
	static ref<IslamicCalendar> new_object(ref<java::util::Locale> aLocale);
	static ref<IslamicCalendar> new_object(ref<android::icu::util::ULocale> locale);
	static ref<IslamicCalendar> new_object(ref<android::icu::util::TimeZone> zone, ref<java::util::Locale> aLocale);
	static ref<IslamicCalendar> new_object(ref<android::icu::util::TimeZone> zone, ref<android::icu::util::ULocale> locale);
	static ref<IslamicCalendar> new_object(ref<java::util::Date> date);
	static ref<IslamicCalendar> new_object(jint year, jint month, jint date);
	static ref<IslamicCalendar> new_object(jint year, jint month, jint date, jint hour, jint minute, jint second);
	void setCalculationType(ref<android::icu::util::IslamicCalendar_CalculationType> type);
	ref<android::icu::util::IslamicCalendar_CalculationType> getCalculationType();
	ref<java::lang::String> getType();

protected:

	IslamicCalendar(handle_type h) : base_(h) {}

};

} // namespace android::icu::util
} // namespace scapix::java_api

#include <scapix/java_api/android/icu/util/IslamicCalendar_CalculationType.h>
#include <scapix/java_api/android/icu/util/TimeZone.h>
#include <scapix/java_api/android/icu/util/ULocale.h>
#include <scapix/java_api/java/lang/String.h>
#include <scapix/java_api/java/util/Date.h>
#include <scapix/java_api/java/util/Locale.h>

namespace scapix::java_api {
namespace android::icu::util {

inline jint IslamicCalendar::DHU_AL_HIJJAH_() { return get_static_field<SCAPIX_META_STRING("DHU_AL_HIJJAH"), jint>(); }
inline jint IslamicCalendar::DHU_AL_QIDAH_() { return get_static_field<SCAPIX_META_STRING("DHU_AL_QIDAH"), jint>(); }
inline jint IslamicCalendar::JUMADA_1_() { return get_static_field<SCAPIX_META_STRING("JUMADA_1"), jint>(); }
inline jint IslamicCalendar::JUMADA_2_() { return get_static_field<SCAPIX_META_STRING("JUMADA_2"), jint>(); }
inline jint IslamicCalendar::MUHARRAM_() { return get_static_field<SCAPIX_META_STRING("MUHARRAM"), jint>(); }
inline jint IslamicCalendar::RABI_1_() { return get_static_field<SCAPIX_META_STRING("RABI_1"), jint>(); }
inline jint IslamicCalendar::RABI_2_() { return get_static_field<SCAPIX_META_STRING("RABI_2"), jint>(); }
inline jint IslamicCalendar::RAJAB_() { return get_static_field<SCAPIX_META_STRING("RAJAB"), jint>(); }
inline jint IslamicCalendar::RAMADAN_() { return get_static_field<SCAPIX_META_STRING("RAMADAN"), jint>(); }
inline jint IslamicCalendar::SAFAR_() { return get_static_field<SCAPIX_META_STRING("SAFAR"), jint>(); }
inline jint IslamicCalendar::SHABAN_() { return get_static_field<SCAPIX_META_STRING("SHABAN"), jint>(); }
inline jint IslamicCalendar::SHAWWAL_() { return get_static_field<SCAPIX_META_STRING("SHAWWAL"), jint>(); }
inline ref<IslamicCalendar> IslamicCalendar::new_object() { return base_::new_object(); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(ref<android::icu::util::TimeZone> zone) { return base_::new_object(zone); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(ref<java::util::Locale> aLocale) { return base_::new_object(aLocale); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(ref<android::icu::util::ULocale> locale) { return base_::new_object(locale); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(ref<android::icu::util::TimeZone> zone, ref<java::util::Locale> aLocale) { return base_::new_object(zone, aLocale); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(ref<android::icu::util::TimeZone> zone, ref<android::icu::util::ULocale> locale) { return base_::new_object(zone, locale); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(ref<java::util::Date> date) { return base_::new_object(date); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(jint year, jint month, jint date) { return base_::new_object(year, month, date); }
inline ref<IslamicCalendar> IslamicCalendar::new_object(jint year, jint month, jint date, jint hour, jint minute, jint second) { return base_::new_object(year, month, date, hour, minute, second); }
inline void IslamicCalendar::setCalculationType(ref<android::icu::util::IslamicCalendar_CalculationType> type) { return call_method<SCAPIX_META_STRING("setCalculationType"), void>(type); }
inline ref<android::icu::util::IslamicCalendar_CalculationType> IslamicCalendar::getCalculationType() { return call_method<SCAPIX_META_STRING("getCalculationType"), ref<android::icu::util::IslamicCalendar_CalculationType>>(); }
inline ref<java::lang::String> IslamicCalendar::getType() { return call_method<SCAPIX_META_STRING("getType"), ref<java::lang::String>>(); }

} // namespace android::icu::util
} // namespace scapix::java_api

#endif // SCAPIX_ANDROID_ICU_UTIL_ISLAMICCALENDAR_H
